Mar 18 00:43:56 localhost polkitd[886]: Loading rules from directory /etc/polkit-1/rules.d
Mar 18 00:43:56 localhost polkitd[886]: Loading rules from directory /usr/share/polkit-1/rules.d
Mar 18 00:43:56 localhost polkitd[886]: Finished loading, compiling and executing 10 rules
Mar 18 00:43:56 localhost polkitd[886]: Acquired the name org.freedesktop.PolicyKit1 on the system bus
Mar 18 00:44:02 localhost sshd[1133]: Server listening on 0.0.0.0 port 22.
Mar 18 00:44:02 localhost sshd[1133]: Server listening on :: port 22.
Mar 18 00:45:15 localhost systemd[6163]: pam_unix(systemd-user:session): session opened for user gdm by (uid=0)
Mar 18 00:45:15 localhost gdm-launch-environment][6157]: pam_unix(gdm-launch-environment:session): session opened for user gdm by (uid=0)
Mar 18 00:45:19 localhost polkitd[886]: Registered Authentication Agent for unix-session:c1 (system bus name :1.44 [/usr/bin/gnome-shell], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Mar 18 00:45:40 localhost systemd[6469]: pam_unix(systemd-user:session): session opened for user sfagbohoun by (uid=0)
Mar 18 00:45:40 localhost gdm-password][6460]: pam_unix(gdm-password:session): session opened for user sfagbohoun by (uid=0)
Mar 18 00:45:43 localhost polkitd[886]: Registered Authentication Agent for unix-session:2 (system bus name :1.218 [/usr/bin/gnome-shell], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Mar 30 23:56:03 localhost polkitd[868]: Loading rules from directory /etc/polkit-1/rules.d
Mar 30 23:56:03 localhost polkitd[868]: Loading rules from directory /usr/share/polkit-1/rules.d
Mar 30 23:56:03 localhost polkitd[868]: Finished loading, compiling and executing 10 rules
Mar 30 23:56:03 localhost polkitd[868]: Acquired the name org.freedesktop.PolicyKit1 on the system bus
Mar 30 23:56:07 localhost sshd[1049]: Server listening on 0.0.0.0 port 22.
Mar 30 23:56:07 localhost sshd[1049]: Server listening on :: port 22.
Mar 30 23:56:14 localhost systemd[1350]: pam_unix(systemd-user:session): session opened for user gdm by (uid=0)
Mar 30 23:56:15 localhost gdm-launch-environment][1324]: pam_unix(gdm-launch-environment:session): session opened for user gdm by (uid=0)
Mar 30 23:56:26 localhost polkitd[868]: Registered Authentication Agent for unix-session:c1 (system bus name :1.35 [/usr/bin/gnome-shell], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Mar 30 23:56:41 localhost systemd[2072]: pam_unix(systemd-user:session): session opened for user sfagbohoun by (uid=0)
Mar 30 23:56:41 localhost gdm-password][2061]: pam_unix(gdm-password:session): session opened for user sfagbohoun by (uid=0)
Mar 30 23:56:45 localhost polkitd[868]: Registered Authentication Agent for unix-session:2 (system bus name :1.214 [/usr/bin/gnome-shell], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Mar 30 23:58:42 localhost su[2942]: pam_systemd(su-l:session): Cannot create session: Already running in a session or user slice
Mar 30 23:58:42 localhost su[2942]: pam_unix(su-l:session): session opened for user root by (uid=1000)
Mar 30 23:58:56 localhost useradd[2976]: new group: name=ansible, GID=1001
Mar 30 23:58:56 localhost useradd[2976]: new user: name=ansible, UID=1001, GID=1001, home=/home/ansible, shell=/bin/bash
Mar 30 23:59:18 localhost passwd[3005]: pam_unix(passwd:chauthtok): password changed for ansible
Mar 30 23:59:18 localhost passwd[3005]: gkr-pam: couldn't update the login keyring password: no old password was entered
Mar 31 00:08:32 localhost sshd[3247]: Accepted password for ansible from 192.168.1.217 port 58508 ssh2
Mar 31 00:08:32 localhost sshd[3251]: Accepted password for ansible from 192.168.1.217 port 58509 ssh2
Mar 31 00:08:32 localhost systemd[3254]: pam_unix(systemd-user:session): session opened for user ansible by (uid=0)
Mar 31 00:08:32 localhost sshd[3251]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 31 00:08:32 localhost sshd[3247]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 31 00:09:35 localhost sudo[3405]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/bash
Mar 31 00:09:35 localhost sudo[3405]: pam_systemd(sudo-i:session): Cannot create session: Already running in a session or user slice
Mar 31 00:09:35 localhost sudo[3405]: pam_unix(sudo-i:session): session opened for user root by ansible(uid=0)
Mar 31 00:11:09 localhost sshd[3468]: Connection closed by authenticating user ansible 192.168.1.136 port 35330 [preauth]
Mar 31 00:11:09 localhost sshd[3472]: Connection closed by authenticating user ansible 192.168.1.136 port 35332 [preauth]
Mar 31 00:11:12 localhost sshd[3474]: Accepted password for ansible from 192.168.1.136 port 35334 ssh2
Mar 31 00:11:12 localhost sshd[3474]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 31 00:11:12 localhost sshd[3480]: Received disconnect from 192.168.1.136 port 35334:11: disconnected by user
Mar 31 00:11:12 localhost sshd[3480]: Disconnected from user ansible 192.168.1.136 port 35334
Mar 31 00:11:12 localhost sshd[3474]: pam_unix(sshd:session): session closed for user ansible
Mar 31 00:18:39 localhost sshd[3639]: Connection closed by 192.168.1.136 port 35476 [preauth]
Mar 31 00:18:58 localhost sshd[3641]: Accepted publickey for ansible from 192.168.1.136 port 35482 ssh2: RSA SHA256:jpchiL+jLX3smTuII7SubLqdvcmq8e3I+5HSG4oUreQ
Mar 31 00:18:58 localhost sshd[3641]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 31 00:20:00 localhost sshd[3644]: Received disconnect from 192.168.1.136 port 35482:11: disconnected by user
Mar 31 00:20:00 localhost sshd[3644]: Disconnected from user ansible 192.168.1.136 port 35482
Mar 31 00:20:00 localhost sshd[3641]: pam_unix(sshd:session): session closed for user ansible
Mar 31 00:34:25 localhost sshd[4075]: Accepted publickey for ansible from 192.168.1.136 port 35488 ssh2: RSA SHA256:jpchiL+jLX3smTuII7SubLqdvcmq8e3I+5HSG4oUreQ
Mar 31 00:34:25 localhost sshd[4075]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 31 00:34:26 localhost sudo[4238]: ansible : TTY=pts/2 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-difglhszxfgzkcyvqbclgptjmsfjkaej ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1617165265.469127-33827-175085040709530/AnsiballZ_setup.py
Mar 31 00:34:26 localhost sudo[4238]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 31 00:34:26 localhost sudo[4238]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 31 00:34:28 localhost sudo[4238]: pam_unix(sudo:session): session closed for user root
Mar 31 00:35:05 localhost sudo[4459]: ansible : TTY=pts/2 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-kfpwhffsoadfqwnshiexdhnobwcjqfin ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1617165304.6813672-34131-22532331484984/AnsiballZ_setup.py
Mar 31 00:35:05 localhost sudo[4459]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 31 00:35:05 localhost sudo[4459]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 31 00:35:06 localhost sudo[4459]: pam_unix(sudo:session): session closed for user root
Mar 31 00:35:08 localhost sudo[4645]: ansible : TTY=pts/2 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-knwmuiujamxlpsizofxzmirhkrzknekp ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1617165307.5949407-34382-63871529477926/AnsiballZ_user.py
Mar 31 00:35:08 localhost sudo[4645]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 31 00:35:08 localhost sudo[4645]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 31 00:35:08 localhost useradd[4652]: new group: name=stan, GID=2021
Mar 31 00:35:08 localhost useradd[4652]: new user: name=stan, UID=2021, GID=2021, home=/home/stan, shell=/bin/bash
Mar 31 00:35:10 localhost sudo[4645]: pam_unix(sudo:session): session closed for user root
Mar 31 00:35:10 localhost sudo[4790]: ansible : TTY=pts/2 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-yxdbizjdorwfjcdznovkqyttgjruxnan ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1617165310.2476351-34382-130485765417421/AnsiballZ_user.py
Mar 31 00:35:10 localhost sudo[4790]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 31 00:35:10 localhost sudo[4790]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 31 00:35:11 localhost useradd[4797]: new group: name=favor, GID=2022
Mar 31 00:35:11 localhost useradd[4797]: new user: name=favor, UID=2022, GID=2022, home=/home/favor, shell=/bin/bash
Mar 31 00:35:12 localhost sudo[4790]: pam_unix(sudo:session): session closed for user root
Mar 31 00:35:13 localhost sudo[4934]: ansible : TTY=pts/2 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-qjmlmhsxoorkvdcyfdeppvoyhhrlrioj ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1617165312.61571-34382-259331406750403/AnsiballZ_user.py
Mar 31 00:35:13 localhost sudo[4934]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 31 00:35:13 localhost sudo[4934]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 31 00:35:13 localhost useradd[4941]: new group: name=blessing, GID=2023
Mar 31 00:35:13 localhost useradd[4941]: new user: name=blessing, UID=2023, GID=2023, home=/home/blessing, shell=/bin/bash
Mar 31 00:35:14 localhost sudo[4934]: pam_unix(sudo:session): session closed for user root
Mar 31 00:36:14 localhost sshd[4078]: Received disconnect from 192.168.1.136 port 35488:11: disconnected by user
Mar 31 00:36:14 localhost sshd[4078]: Disconnected from user ansible 192.168.1.136 port 35488
Mar 31 00:36:14 localhost sshd[4075]: pam_unix(sshd:session): session closed for user ansible
Mar 31 00:37:07 localhost sshd[5015]: Accepted publickey for ansible from 192.168.1.136 port 35494 ssh2: RSA SHA256:jpchiL+jLX3smTuII7SubLqdvcmq8e3I+5HSG4oUreQ
Mar 31 00:37:07 localhost sshd[5015]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 31 00:37:09 localhost sudo[5180]: ansible : TTY=pts/2 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-sheuitsyxrfxhamdduybycllntliybnn ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1617165427.9619584-34948-65723606074374/AnsiballZ_setup.py
Mar 31 00:37:09 localhost sudo[5180]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 31 00:37:09 localhost sudo[5180]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 31 00:37:10 localhost sudo[5180]: pam_unix(sudo:session): session closed for user root
Mar 31 00:37:11 localhost sudo[5357]: ansible : TTY=pts/2 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-jhvshdwtmgzpytdijmnpkqgckyzdfyxn ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1617165430.9045987-35222-24912576364858/AnsiballZ_user.py
Mar 31 00:37:11 localhost sudo[5357]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 31 00:37:11 localhost sudo[5357]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 31 00:37:12 localhost sudo[5357]: pam_unix(sudo:session): session closed for user root
Mar 31 00:37:12 localhost sudo[5495]: ansible : TTY=pts/2 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-uwphbojonlfshqkpsrjkcwfxyaebgolp ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1617165432.3206656-35222-181068495934017/AnsiballZ_user.py
Mar 31 00:37:12 localhost sudo[5495]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 31 00:37:12 localhost sudo[5495]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 31 00:37:13 localhost sudo[5495]: pam_unix(sudo:session): session closed for user root
Mar 31 00:37:13 localhost sudo[5631]: ansible : TTY=pts/2 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-kdpgokuvaagipwpqvrvdmyjrtbfrgihv ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1617165433.3289754-35222-2113360676274/AnsiballZ_user.py
Mar 31 00:37:13 localhost sudo[5631]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 31 00:37:13 localhost sudo[5631]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 31 00:37:14 localhost sudo[5631]: pam_unix(sudo:session): session closed for user root
Mar 31 00:38:14 localhost sshd[5018]: Received disconnect from 192.168.1.136 port 35494:11: disconnected by user
Mar 31 00:38:14 localhost sshd[5018]: Disconnected from user ansible 192.168.1.136 port 35494
Mar 31 00:38:14 localhost sshd[5015]: pam_unix(sshd:session): session closed for user ansible
Mar 31 00:53:49 localhost sshd[5909]: Accepted publickey for ansible from 192.168.1.136 port 35500 ssh2: RSA SHA256:jpchiL+jLX3smTuII7SubLqdvcmq8e3I+5HSG4oUreQ
Mar 31 00:53:49 localhost sshd[5909]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 31 00:53:51 localhost sudo[6072]: ansible : TTY=pts/2 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-khqgnllrqpknczklaxxicodoorocaivg ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1617166429.7915766-36048-195105261658928/AnsiballZ_setup.py
Mar 31 00:53:51 localhost sudo[6072]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 31 00:53:51 localhost sudo[6072]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 31 00:53:52 localhost sudo[6072]: pam_unix(sudo:session): session closed for user root
Mar 31 00:54:52 localhost sshd[5912]: Received disconnect from 192.168.1.136 port 35500:11: disconnected by user
Mar 31 00:54:52 localhost sshd[5912]: Disconnected from user ansible 192.168.1.136 port 35500
Mar 31 00:54:52 localhost sshd[5909]: pam_unix(sshd:session): session closed for user ansible
Mar 31 00:54:52 localhost sshd[6169]: Accepted publickey for ansible from 192.168.1.136 port 35506 ssh2: RSA SHA256:jpchiL+jLX3smTuII7SubLqdvcmq8e3I+5HSG4oUreQ
Mar 31 00:54:53 localhost sshd[6169]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 31 00:54:54 localhost sudo[6340]: ansible : TTY=pts/2 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ctosecyytarehkiveigdehtovkqlxwbz ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1617166493.2593243-36356-94056045011929/AnsiballZ_setup.py
Mar 31 00:54:54 localhost sudo[6340]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 31 00:54:54 localhost sudo[6340]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 31 00:54:55 localhost sudo[6340]: pam_unix(sudo:session): session closed for user root
Mar 31 00:55:56 localhost sshd[6180]: Received disconnect from 192.168.1.136 port 35506:11: disconnected by user
Mar 31 00:55:56 localhost sshd[6180]: Disconnected from user ansible 192.168.1.136 port 35506
Mar 31 00:55:56 localhost sshd[6169]: pam_unix(sshd:session): session closed for user ansible
Mar 31 00:57:47 localhost sshd[6484]: Accepted publickey for ansible from 192.168.1.136 port 35510 ssh2: RSA SHA256:jpchiL+jLX3smTuII7SubLqdvcmq8e3I+5HSG4oUreQ
Mar 31 00:57:47 localhost sshd[6484]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 31 00:57:50 localhost sudo[6647]: ansible : TTY=pts/2 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-noohobxuuxwhojhywcxhyyrhduivlqkb ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1617166668.5989354-36759-118664134010367/AnsiballZ_setup.py
Mar 31 00:57:50 localhost sudo[6647]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 31 00:57:50 localhost sudo[6647]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 31 00:57:50 localhost sudo[6647]: pam_unix(sudo:session): session closed for user root
Mar 31 00:58:51 localhost sshd[6487]: Received disconnect from 192.168.1.136 port 35510:11: disconnected by user
Mar 31 00:58:51 localhost sshd[6487]: Disconnected from user ansible 192.168.1.136 port 35510
Mar 31 00:58:51 localhost sshd[6484]: pam_unix(sshd:session): session closed for user ansible
Mar 31 01:01:08 localhost sshd[6789]: Accepted publickey for ansible from 192.168.1.136 port 35518 ssh2: RSA SHA256:jpchiL+jLX3smTuII7SubLqdvcmq8e3I+5HSG4oUreQ
Mar 31 01:01:08 localhost sshd[6789]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 31 01:01:10 localhost sudo[6952]: ansible : TTY=pts/2 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-iylgiluofzcocjbotjlevanogfqalujt ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1617166869.1805072-37141-183843667056879/AnsiballZ_setup.py
Mar 31 01:01:10 localhost sudo[6952]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 31 01:01:10 localhost sudo[6952]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 31 01:01:11 localhost sudo[6952]: pam_unix(sudo:session): session closed for user root
Mar 31 01:02:11 localhost sshd[6792]: Received disconnect from 192.168.1.136 port 35518:11: disconnected by user
Mar 31 01:02:11 localhost sshd[6792]: Disconnected from user ansible 192.168.1.136 port 35518
Mar 31 01:02:11 localhost sshd[6789]: pam_unix(sshd:session): session closed for user ansible
Mar 31 01:02:59 localhost sshd[7063]: Accepted publickey for ansible from 192.168.1.136 port 35524 ssh2: RSA SHA256:jpchiL+jLX3smTuII7SubLqdvcmq8e3I+5HSG4oUreQ
Mar 31 01:02:59 localhost sshd[7063]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 31 01:03:01 localhost sudo[7226]: ansible : TTY=pts/2 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-iwblxmztlmuoilfuszkpiusesrcqpyhu ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1617166980.1765938-37490-88165800931033/AnsiballZ_setup.py
Mar 31 01:03:01 localhost sudo[7226]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 31 01:03:01 localhost sudo[7226]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 31 01:03:02 localhost sudo[7226]: pam_unix(sudo:session): session closed for user root
Mar 31 01:03:53 localhost sudo[7458]: ansible : TTY=pts/2 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-fdgqwvxilduqvqcburbqgxsmbkhvwroh ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1617167031.8435023-37788-103217229649132/AnsiballZ_setup.py
Mar 31 01:03:53 localhost sudo[7458]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 31 01:03:53 localhost sudo[7458]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 31 01:03:54 localhost sudo[7458]: pam_unix(sudo:session): session closed for user root
Mar 31 01:03:55 localhost sudo[7635]: ansible : TTY=pts/2 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-lvickwdarvouesuseenomnttosvyntfg ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1617167034.7811599-38039-203233460384610/AnsiballZ_stat.py
Mar 31 01:03:55 localhost sudo[7635]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 31 01:03:55 localhost sudo[7635]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 31 01:03:55 localhost sudo[7635]: pam_unix(sudo:session): session closed for user root
Mar 31 01:03:56 localhost sudo[7743]: ansible : TTY=pts/2 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-htqnswvikicaqpwgofgxowawkfftbymp ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1617167034.7811599-38039-203233460384610/AnsiballZ_copy.py
Mar 31 01:03:56 localhost sudo[7743]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 31 01:03:56 localhost sudo[7743]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 31 01:03:57 localhost sudo[7743]: pam_unix(sudo:session): session closed for user root
Mar 31 01:03:57 localhost sudo[7878]: ansible : TTY=pts/2 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ghlbspmbozacclokkunkiudynmkzehxo ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1617167037.4451303-38039-182007761870959/AnsiballZ_stat.py
Mar 31 01:03:57 localhost sudo[7878]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 31 01:03:57 localhost sudo[7878]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 31 01:03:58 localhost sudo[7878]: pam_unix(sudo:session): session closed for user root
Mar 31 01:03:58 localhost sudo[7949]: ansible : TTY=pts/2 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-azoimeqsdaldeifywxoxasvvtwnmifif ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1617167037.4451303-38039-182007761870959/AnsiballZ_file.py
Mar 31 01:03:58 localhost sudo[7949]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 31 01:03:58 localhost sudo[7949]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 31 01:03:59 localhost sudo[7949]: pam_unix(sudo:session): session closed for user root
Mar 31 01:03:59 localhost sudo[8082]: ansible : TTY=pts/2 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-zhstmmnazizzctmpfduhsbguyvmmczrc ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1617167039.4454474-38039-161592280355064/AnsiballZ_stat.py
Mar 31 01:03:59 localhost sudo[8082]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 31 01:03:59 localhost sudo[8082]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 31 01:04:00 localhost sudo[8082]: pam_unix(sudo:session): session closed for user root
Mar 31 01:04:00 localhost sudo[8153]: ansible : TTY=pts/2 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-erpwoicaguleubfrmqbbycuzbxghdznm ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1617167039.4454474-38039-161592280355064/AnsiballZ_file.py
Mar 31 01:04:00 localhost sudo[8153]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 31 01:04:00 localhost sudo[8153]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 31 01:04:01 localhost sudo[8153]: pam_unix(sudo:session): session closed for user root
Mar 31 01:05:01 localhost sshd[7066]: Received disconnect from 192.168.1.136 port 35524:11: disconnected by user
Mar 31 01:05:01 localhost sshd[7066]: Disconnected from user ansible 192.168.1.136 port 35524
Mar 31 01:05:01 localhost sshd[7063]: pam_unix(sshd:session): session closed for user ansible
Mar 31 01:06:01 localhost sshd[8228]: Accepted publickey for ansible from 192.168.1.136 port 35530 ssh2: RSA SHA256:jpchiL+jLX3smTuII7SubLqdvcmq8e3I+5HSG4oUreQ
Mar 31 01:06:01 localhost sshd[8228]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 31 01:06:03 localhost sudo[8391]: ansible : TTY=pts/2 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-foznzebkjhxvgtutuolbnwapphjoxnav ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1617167162.3291843-38893-32333444845795/AnsiballZ_setup.py
Mar 31 01:06:03 localhost sudo[8391]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 31 01:06:03 localhost sudo[8391]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 31 01:06:04 localhost sudo[8391]: pam_unix(sudo:session): session closed for user root
Mar 31 01:06:06 localhost sudo[8568]: ansible : TTY=pts/2 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-tshhxmiyskrfiprsbndivlilvfijkasm ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1617167165.47415-39167-150657174175959/AnsiballZ_stat.py
Mar 31 01:06:06 localhost sudo[8568]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 31 01:06:06 localhost sudo[8568]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 31 01:06:06 localhost sudo[8568]: pam_unix(sudo:session): session closed for user root
Mar 31 01:06:07 localhost sudo[8640]: ansible : TTY=pts/2 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-xtvgqxcpcgaslrbdwoyknsesiajbtqvi ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1617167165.47415-39167-150657174175959/AnsiballZ_file.py
Mar 31 01:06:07 localhost sudo[8640]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 31 01:06:07 localhost sudo[8640]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 31 01:06:07 localhost sudo[8640]: pam_unix(sudo:session): session closed for user root
Mar 31 01:06:08 localhost sudo[8781]: ansible : TTY=pts/2 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-lhfncarmbecxmexarlwgufesvcqrugct ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1617167167.7627287-39167-236383808228960/AnsiballZ_stat.py
Mar 31 01:06:08 localhost sudo[8781]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 31 01:06:08 localhost sudo[8781]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 31 01:06:08 localhost sudo[8781]: pam_unix(sudo:session): session closed for user root
Mar 31 01:06:08 localhost sudo[8852]: ansible : TTY=pts/2 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-nggjaxfefzfxxadywljwdmvhuhfhamhs ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1617167167.7627287-39167-236383808228960/AnsiballZ_file.py
Mar 31 01:06:08 localhost sudo[8852]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 31 01:06:08 localhost sudo[8852]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 31 01:06:09 localhost sudo[8852]: pam_unix(sudo:session): session closed for user root
Mar 31 01:06:09 localhost sudo[8985]: ansible : TTY=pts/2 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-twuyvrjdvrpzbprtwnhqkrsjhtdtydfl ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1617167169.3865972-39167-34329774976712/AnsiballZ_stat.py
Mar 31 01:06:09 localhost sudo[8985]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 31 01:06:09 localhost sudo[8985]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 31 01:06:10 localhost sudo[8985]: pam_unix(sudo:session): session closed for user root
Mar 31 01:06:10 localhost sudo[9056]: ansible : TTY=pts/2 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-elunmbxppnwrrsqxbkemdtlmascgriqa ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1617167169.3865972-39167-34329774976712/AnsiballZ_file.py
Mar 31 01:06:10 localhost sudo[9056]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 31 01:06:10 localhost sudo[9056]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 31 01:06:10 localhost sudo[9056]: pam_unix(sudo:session): session closed for user root
Mar 31 01:07:10 localhost sshd[8231]: Received disconnect from 192.168.1.136 port 35530:11: disconnected by user
Mar 31 01:07:10 localhost sshd[8231]: Disconnected from user ansible 192.168.1.136 port 35530
Mar 31 01:07:10 localhost sshd[8228]: pam_unix(sshd:session): session closed for user ansible
Mar 31 01:07:39 localhost sshd[9126]: Accepted publickey for ansible from 192.168.1.136 port 35534 ssh2: RSA SHA256:jpchiL+jLX3smTuII7SubLqdvcmq8e3I+5HSG4oUreQ
Mar 31 01:07:39 localhost sshd[9126]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 31 01:07:41 localhost sudo[9289]: ansible : TTY=pts/2 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-rbaduqgyyrwkrxaitwodasxrgadknjcs ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1617167260.0214-39942-252367921223618/AnsiballZ_setup.py
Mar 31 01:07:41 localhost sudo[9289]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 31 01:07:41 localhost sudo[9289]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 31 01:07:42 localhost sudo[9289]: pam_unix(sudo:session): session closed for user root
Mar 31 01:07:43 localhost sudo[9466]: ansible : TTY=pts/2 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-udrwsiiigijfzravehpjvdzxkyfozdvu ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1617167262.9945714-40216-82451176148582/AnsiballZ_stat.py
Mar 31 01:07:43 localhost sudo[9466]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 31 01:07:43 localhost sudo[9466]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 31 01:07:44 localhost sudo[9466]: pam_unix(sudo:session): session closed for user root
Mar 31 01:07:44 localhost sudo[9537]: ansible : TTY=pts/2 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-oehefsvjgtonongxblwxmyzvkukwrhaq ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1617167262.9945714-40216-82451176148582/AnsiballZ_file.py
Mar 31 01:07:44 localhost sudo[9537]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 31 01:07:44 localhost sudo[9537]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 31 01:07:45 localhost sudo[9537]: pam_unix(sudo:session): session closed for user root
Mar 31 01:07:45 localhost sudo[9670]: ansible : TTY=pts/2 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-shxcrchnsffwlpzigdpeshpcoqnlikud ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1617167265.219551-40216-263951032724473/AnsiballZ_stat.py
Mar 31 01:07:45 localhost sudo[9670]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 31 01:07:45 localhost sudo[9670]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 31 01:07:45 localhost sudo[9670]: pam_unix(sudo:session): session closed for user root
Mar 31 01:07:46 localhost sudo[9741]: ansible : TTY=pts/2 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-xhilfjbenhluqdxwcnxgeaayidmuohyj ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1617167265.219551-40216-263951032724473/AnsiballZ_file.py
Mar 31 01:07:46 localhost sudo[9741]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 31 01:07:46 localhost sudo[9741]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 31 01:07:46 localhost sudo[9741]: pam_unix(sudo:session): session closed for user root
Mar 31 01:07:47 localhost sudo[9874]: ansible : TTY=pts/2 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-lggnzybpmnwlnxppeljioqfqmhyebcou ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1617167266.8330932-40216-39441175002015/AnsiballZ_stat.py
Mar 31 01:07:47 localhost sudo[9874]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 31 01:07:47 localhost sudo[9874]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 31 01:07:47 localhost sudo[9874]: pam_unix(sudo:session): session closed for user root
Mar 31 01:07:47 localhost sudo[9945]: ansible : TTY=pts/2 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-xmakswgwxornrjiaicnvqljdkznysthn ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1617167266.8330932-40216-39441175002015/AnsiballZ_file.py
Mar 31 01:07:47 localhost sudo[9945]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 31 01:07:47 localhost sudo[9945]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 31 01:07:48 localhost sudo[9945]: pam_unix(sudo:session): session closed for user root
Mar 31 01:08:48 localhost sshd[9129]: Received disconnect from 192.168.1.136 port 35534:11: disconnected by user
Mar 31 01:08:48 localhost sshd[9129]: Disconnected from user ansible 192.168.1.136 port 35534
Mar 31 01:08:48 localhost sshd[9126]: pam_unix(sshd:session): session closed for user ansible
Mar 31 01:10:29 localhost sshd[10033]: Accepted publickey for ansible from 192.168.1.136 port 35542 ssh2: RSA SHA256:jpchiL+jLX3smTuII7SubLqdvcmq8e3I+5HSG4oUreQ
Mar 31 01:10:29 localhost sshd[10033]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 31 01:10:30 localhost sudo[10196]: ansible : TTY=pts/2 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-pdeikxuubquxctyggbkrekyvmxcuetjf ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1617167429.454067-41020-137831215719761/AnsiballZ_setup.py
Mar 31 01:10:30 localhost sudo[10196]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 31 01:10:30 localhost sudo[10196]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 31 01:10:31 localhost sudo[10196]: pam_unix(sudo:session): session closed for user root
Mar 31 01:11:31 localhost sshd[10036]: Received disconnect from 192.168.1.136 port 35542:11: disconnected by user
Mar 31 01:11:31 localhost sshd[10036]: Disconnected from user ansible 192.168.1.136 port 35542
Mar 31 01:11:31 localhost sshd[10033]: pam_unix(sshd:session): session closed for user ansible
Mar 31 01:24:16 localhost sshd[10483]: Accepted publickey for ansible from 192.168.1.136 port 35548 ssh2: RSA SHA256:jpchiL+jLX3smTuII7SubLqdvcmq8e3I+5HSG4oUreQ
Mar 31 01:24:16 localhost sshd[10483]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 31 01:24:18 localhost sudo[10648]: ansible : TTY=pts/2 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-kimkzlqnbrlytsendpptusckribkjjki ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1617168256.7807295-41586-145761504607063/AnsiballZ_setup.py
Mar 31 01:24:18 localhost sudo[10648]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 31 01:24:18 localhost sudo[10648]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 31 01:24:18 localhost sudo[10648]: pam_unix(sudo:session): session closed for user root
Mar 31 01:25:05 localhost sudo[10867]: ansible : TTY=pts/2 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-acmhbopswfzfogxkemyanpjmynwncwps ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1617168304.6474817-41896-133005901302533/AnsiballZ_setup.py
Mar 31 01:25:05 localhost sudo[10867]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 31 01:25:05 localhost sudo[10867]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 31 01:25:06 localhost sudo[10867]: pam_unix(sudo:session): session closed for user root
Mar 31 01:26:06 localhost sshd[10486]: Received disconnect from 192.168.1.136 port 35548:11: disconnected by user
Mar 31 01:26:06 localhost sshd[10486]: Disconnected from user ansible 192.168.1.136 port 35548
Mar 31 01:26:07 localhost sshd[10483]: pam_unix(sshd:session): session closed for user ansible
May 29 00:00:16 node2 polkitd[875]: Loading rules from directory /etc/polkit-1/rules.d
May 29 00:00:16 node2 polkitd[875]: Loading rules from directory /usr/share/polkit-1/rules.d
May 29 00:00:17 node2 polkitd[875]: Finished loading, compiling and executing 10 rules
May 29 00:00:17 node2 polkitd[875]: Acquired the name org.freedesktop.PolicyKit1 on the system bus
May 29 00:00:23 node2 sshd[1062]: Server listening on 0.0.0.0 port 22.
May 29 00:00:23 node2 sshd[1062]: Server listening on :: port 22.
May 29 00:00:31 node2 systemd[1360]: pam_unix(systemd-user:session): session opened for user gdm by (uid=0)
May 29 00:00:32 node2 gdm-launch-environment][1335]: pam_unix(gdm-launch-environment:session): session opened for user gdm by (uid=0)
May 29 00:00:51 node2 polkitd[875]: Registered Authentication Agent for unix-session:c1 (system bus name :1.37 [/usr/bin/gnome-shell], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
May 29 00:05:59 node2 systemd[2133]: pam_unix(systemd-user:session): session opened for user ansible by (uid=0)
May 29 00:06:00 node2 gdm-password][2121]: pam_unix(gdm-password:session): session opened for user ansible by (uid=0)
May 29 00:06:04 node2 polkitd[875]: Registered Authentication Agent for unix-session:2 (system bus name :1.227 [/usr/bin/gnome-shell], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
May 29 00:07:58 node2 su[3067]: pam_systemd(su-l:session): Cannot create session: Already running in a session or user slice
May 29 00:07:58 node2 su[3067]: pam_unix(su-l:session): session opened for user root by (uid=1001)
May 29 00:19:14 node2 sshd[3309]: Accepted password for ansible from 192.168.1.217 port 51601 ssh2
May 29 00:19:14 node2 sshd[3309]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
May 29 00:19:14 node2 sshd[3313]: Accepted password for ansible from 192.168.1.217 port 51602 ssh2
May 29 00:19:14 node2 sshd[3313]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
May 29 00:22:14 node2 sudo[3432]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/su -
May 29 00:22:14 node2 sudo[3432]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
May 29 00:22:14 node2 sudo[3432]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
May 29 00:22:14 node2 su[3434]: pam_systemd(su-l:session): Cannot create session: Already running in a session or user slice
May 29 00:22:14 node2 su[3434]: pam_unix(su-l:session): session opened for user root by ansible(uid=0)
May 29 01:15:10 node2 gdm-password][4258]: gkr-pam: unlocked login keyring
May 29 02:29:06 node2 sshd[5454]: Accepted publickey for ansible from 192.168.1.136 port 56752 ssh2: RSA SHA256:jpchiL+jLX3smTuII7SubLqdvcmq8e3I+5HSG4oUreQ
May 29 02:29:06 node2 sshd[5454]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
May 29 02:30:09 node2 sshd[5457]: Received disconnect from 192.168.1.136 port 56752:11: disconnected by user
May 29 02:30:09 node2 sshd[5457]: Disconnected from user ansible 192.168.1.136 port 56752
May 29 02:30:09 node2 sshd[5454]: pam_unix(sshd:session): session closed for user ansible
May 29 02:32:00 node2 sshd[3313]: pam_unix(sshd:session): session closed for user ansible
May 29 07:41:22 node2 sshd[10227]: Accepted publickey for ansible from 192.168.1.136 port 56816 ssh2: RSA SHA256:jpchiL+jLX3smTuII7SubLqdvcmq8e3I+5HSG4oUreQ
May 29 07:41:22 node2 sshd[10227]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
May 29 07:41:26 node2 sudo[10392]: ansible : TTY=pts/2 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-aersoynkznzjezanjgpqpvghkvyzxdow ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1622288524.113872-10459-190216528827935/AnsiballZ_setup.py
May 29 07:41:26 node2 sudo[10392]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
May 29 07:41:26 node2 sudo[10392]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
May 29 07:41:29 node2 sudo[10392]: pam_unix(sudo:session): session closed for user root
May 29 07:41:40 node2 sudo[10581]: ansible : TTY=pts/2 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-joddenbsdibvgqbxmpmixumyeaiaerdh ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1622288539.3299654-10531-251659904175507/AnsiballZ_authorized_key.py
May 29 07:41:40 node2 sudo[10581]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
May 29 07:41:40 node2 sudo[10581]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
May 29 07:41:42 node2 sudo[10581]: pam_unix(sudo:session): session closed for user root
May 29 07:42:42 node2 sshd[10230]: Received disconnect from 192.168.1.136 port 56816:11: disconnected by user
May 29 07:42:42 node2 sshd[10230]: Disconnected from user ansible 192.168.1.136 port 56816
May 29 07:42:42 node2 sshd[10227]: pam_unix(sshd:session): session closed for user ansible
May 29 07:48:12 node2 sshd[10714]: Accepted publickey for ansible from 192.168.1.136 port 56828 ssh2: RSA SHA256:jpchiL+jLX3smTuII7SubLqdvcmq8e3I+5HSG4oUreQ
May 29 07:48:13 node2 sshd[10714]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
May 29 07:48:16 node2 sudo[10888]: ansible : TTY=pts/2 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-nretukqvdicbgnorcywwhhtieciutoxv ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1622288934.3203557-10647-269523940177454/AnsiballZ_command.py
May 29 07:48:16 node2 sudo[10888]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
May 29 07:48:16 node2 sudo[10888]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
May 29 07:48:17 node2 sudo[10888]: pam_unix(sudo:session): session closed for user root
May 29 07:49:17 node2 sshd[10717]: Received disconnect from 192.168.1.136 port 56828:11: disconnected by user
May 29 07:49:17 node2 sshd[10717]: Disconnected from user ansible 192.168.1.136 port 56828
May 29 07:49:17 node2 sshd[10714]: pam_unix(sshd:session): session closed for user ansible
May 29 07:53:49 node2 sshd[11021]: Accepted publickey for ansible from 192.168.1.136 port 56834 ssh2: RSA SHA256:jpchiL+jLX3smTuII7SubLqdvcmq8e3I+5HSG4oUreQ
May 29 07:53:49 node2 sshd[11021]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
May 29 07:53:52 node2 sudo[11185]: ansible : TTY=pts/2 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-lsdfvrgouiayrdxkizydcuqtiqxpphjx ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1622289270.865154-10778-156339294467077/AnsiballZ_stat.py
May 29 07:53:52 node2 sudo[11185]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
May 29 07:53:52 node2 sudo[11185]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
May 29 07:53:53 node2 sudo[11185]: pam_unix(sudo:session): session closed for user root
May 29 07:53:55 node2 sudo[11295]: ansible : TTY=pts/2 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-xmvstpewabnhzhupskyiqburqdhjnvpe ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1622289270.865154-10778-156339294467077/AnsiballZ_copy.py
May 29 07:53:55 node2 sudo[11295]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
May 29 07:53:55 node2 sudo[11295]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
May 29 07:53:56 node2 sudo[11295]: pam_unix(sudo:session): session closed for user root
May 29 07:54:56 node2 sshd[11024]: Received disconnect from 192.168.1.136 port 56834:11: disconnected by user
May 29 07:54:56 node2 sshd[11024]: Disconnected from user ansible 192.168.1.136 port 56834
May 29 07:54:56 node2 sshd[11021]: pam_unix(sshd:session): session closed for user ansible
May 29 07:55:09 node2 sshd[11359]: Accepted publickey for ansible from 192.168.1.136 port 56848 ssh2: RSA SHA256:jpchiL+jLX3smTuII7SubLqdvcmq8e3I+5HSG4oUreQ
May 29 07:55:09 node2 sshd[11359]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
May 29 07:55:12 node2 sudo[11522]: ansible : TTY=pts/2 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-yclhnedstvmslctwdmbdsaelgrjnower ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1622289351.1719196-10904-216657488151109/AnsiballZ_command.py
May 29 07:55:12 node2 sudo[11522]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
May 29 07:55:12 node2 sudo[11522]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
May 29 07:55:13 node2 sudo[11522]: pam_unix(sudo:session): session closed for user root
May 29 07:55:53 node2 sudo[11711]: ansible : TTY=pts/2 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-pibeutneagveuufslputwidnfsluglff ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1622289391.9623616-10994-5437880540810/AnsiballZ_stat.py
May 29 07:55:53 node2 sudo[11711]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
May 29 07:55:53 node2 sudo[11711]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
May 29 07:55:54 node2 sudo[11711]: pam_unix(sudo:session): session closed for user root
May 29 07:55:56 node2 sudo[11821]: ansible : TTY=pts/2 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-vtunzehrjbvcpsoogmvjsadahimvnltv ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1622289391.9623616-10994-5437880540810/AnsiballZ_copy.py
May 29 07:55:56 node2 sudo[11821]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
May 29 07:55:56 node2 sudo[11821]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
May 29 07:55:57 node2 sudo[11821]: pam_unix(sudo:session): session closed for user root
May 29 07:56:12 node2 sudo[11997]: ansible : TTY=pts/2 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-omivwppeasxfdvsyytkewvhelyrzagsq ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1622289410.6870239-11096-70070211466638/AnsiballZ_command.py
May 29 07:56:12 node2 sudo[11997]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
May 29 07:56:12 node2 sudo[11997]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
May 29 07:56:13 node2 sudo[11997]: pam_unix(sudo:session): session closed for user root
May 29 07:57:13 node2 sshd[11362]: Received disconnect from 192.168.1.136 port 56848:11: disconnected by user
May 29 07:57:13 node2 sshd[11362]: Disconnected from user ansible 192.168.1.136 port 56848
May 29 07:57:13 node2 sshd[11359]: pam_unix(sshd:session): session closed for user ansible
Jun  5 11:06:42 node2 polkitd[880]: Loading rules from directory /etc/polkit-1/rules.d
Jun  5 11:06:42 node2 polkitd[880]: Loading rules from directory /usr/share/polkit-1/rules.d
Jun  5 11:06:42 node2 polkitd[880]: Finished loading, compiling and executing 10 rules
Jun  5 11:06:42 node2 polkitd[880]: Acquired the name org.freedesktop.PolicyKit1 on the system bus
Jun  5 11:06:50 node2 sshd[1066]: Server listening on 0.0.0.0 port 22.
Jun  5 11:06:50 node2 sshd[1066]: Server listening on :: port 22.
Jun  5 11:06:59 node2 systemd[1356]: pam_unix(systemd-user:session): session opened for user gdm by (uid=0)
Jun  5 11:07:00 node2 gdm-launch-environment][1328]: pam_unix(gdm-launch-environment:session): session opened for user gdm by (uid=0)
Jun  5 11:07:20 node2 polkitd[880]: Registered Authentication Agent for unix-session:c1 (system bus name :1.32 [/usr/bin/gnome-shell], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Jun  5 11:39:21 node2 sshd[2367]: Accepted publickey for ansible from 192.168.1.136 port 48246 ssh2: RSA SHA256:jpchiL+jLX3smTuII7SubLqdvcmq8e3I+5HSG4oUreQ
Jun  5 11:39:22 node2 systemd[2371]: pam_unix(systemd-user:session): session opened for user ansible by (uid=0)
Jun  5 11:39:22 node2 sshd[2367]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Jun  5 11:39:28 node2 sudo[2583]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-xocmuxhzpazhnjrjhcmedgkzpfwnjgqg ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1622907563.8053374-3714-114995223270938/AnsiballZ_stat.py
Jun  5 11:39:28 node2 sudo[2583]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun  5 11:39:28 node2 sudo[2583]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun  5 11:39:29 node2 sudo[2583]: pam_unix(sudo:session): session closed for user root
Jun  5 11:39:30 node2 sudo[2654]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-shskovfgprswdxieoqosewfghdbgrbxw ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1622907563.8053374-3714-114995223270938/AnsiballZ_file.py
Jun  5 11:39:30 node2 sudo[2654]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun  5 11:39:30 node2 sudo[2654]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun  5 11:39:31 node2 sudo[2654]: pam_unix(sudo:session): session closed for user root
Jun  5 11:40:31 node2 sshd[2395]: Received disconnect from 192.168.1.136 port 48246:11: disconnected by user
Jun  5 11:40:31 node2 sshd[2395]: Disconnected from user ansible 192.168.1.136 port 48246
Jun  5 11:40:31 node2 sshd[2367]: pam_unix(sshd:session): session closed for user ansible
Jun  5 11:40:32 node2 systemd[2381]: pam_unix(systemd-user:session): session closed for user ansible
Jun  5 12:00:11 node2 sshd[2873]: Accepted publickey for ansible from 192.168.1.136 port 48260 ssh2: RSA SHA256:jpchiL+jLX3smTuII7SubLqdvcmq8e3I+5HSG4oUreQ
Jun  5 12:00:12 node2 systemd[2877]: pam_unix(systemd-user:session): session opened for user ansible by (uid=0)
Jun  5 12:00:13 node2 sshd[2873]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Jun  5 12:00:18 node2 sudo[3088]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-dxkbfpvjfpbpupcroqdynzuktiofuhkn ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1622908813.9794054-4221-104072374523513/AnsiballZ_setup.py
Jun  5 12:00:18 node2 sudo[3088]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun  5 12:00:18 node2 sudo[3088]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun  5 12:00:21 node2 sudo[3088]: pam_unix(sudo:session): session closed for user root
Jun  5 12:00:28 node2 sudo[3265]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-nxzhrvdcswlwfwxualuqoythnnklwajk ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1622908827.5330968-4292-172646274965908/AnsiballZ_stat.py
Jun  5 12:00:28 node2 sudo[3265]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun  5 12:00:28 node2 sudo[3265]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun  5 12:00:29 node2 sudo[3265]: pam_unix(sudo:session): session closed for user root
Jun  5 12:00:31 node2 sudo[3336]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-iqpbnuyxfargmggsnenmrqblpvjvhasl ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1622908827.5330968-4292-172646274965908/AnsiballZ_file.py
Jun  5 12:00:31 node2 sudo[3336]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun  5 12:00:31 node2 sudo[3336]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun  5 12:00:32 node2 sudo[3336]: pam_unix(sudo:session): session closed for user root
Jun  5 12:01:16 node2 sudo[3518]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-glujxaamwlwdjawjuzhhsyigxqrokecw ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1622908874.0935369-4397-57866798157310/AnsiballZ_setup.py
Jun  5 12:01:16 node2 sudo[3518]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun  5 12:01:16 node2 sudo[3518]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun  5 12:01:19 node2 sudo[3518]: pam_unix(sudo:session): session closed for user root
Jun  5 12:01:22 node2 sudo[3695]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ixbmjlosgoyeyddbfglsmykhtmkxalov ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1622908881.0226045-4454-140095904456907/AnsiballZ_stat.py
Jun  5 12:01:22 node2 sudo[3695]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun  5 12:01:22 node2 sudo[3695]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun  5 12:01:23 node2 sudo[3695]: pam_unix(sudo:session): session closed for user root
Jun  5 12:01:24 node2 sudo[3766]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-efgpaqqwdsrwcojyvlqpkdlsopfbosdj ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1622908881.0226045-4454-140095904456907/AnsiballZ_file.py
Jun  5 12:01:24 node2 sudo[3766]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun  5 12:01:24 node2 sudo[3766]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun  5 12:01:25 node2 sudo[3766]: pam_unix(sudo:session): session closed for user root
Jun  5 12:02:26 node2 sshd[2899]: Received disconnect from 192.168.1.136 port 48260:11: disconnected by user
Jun  5 12:02:26 node2 sshd[2899]: Disconnected from user ansible 192.168.1.136 port 48260
Jun  5 12:02:26 node2 sshd[2873]: pam_unix(sshd:session): session closed for user ansible
Jun  5 12:02:26 node2 systemd[2885]: pam_unix(systemd-user:session): session closed for user ansible
Jun 12 11:14:29 node2 polkitd[865]: Loading rules from directory /etc/polkit-1/rules.d
Jun 12 11:14:29 node2 polkitd[865]: Loading rules from directory /usr/share/polkit-1/rules.d
Jun 12 11:14:29 node2 polkitd[865]: Finished loading, compiling and executing 10 rules
Jun 12 11:14:29 node2 polkitd[865]: Acquired the name org.freedesktop.PolicyKit1 on the system bus
Jun 12 11:14:43 node2 sshd[1051]: Server listening on 0.0.0.0 port 22.
Jun 12 11:14:43 node2 sshd[1051]: Server listening on :: port 22.
Jun 12 11:14:57 node2 systemd[1364]: pam_unix(systemd-user:session): session opened for user gdm by (uid=0)
Jun 12 11:15:02 node2 gdm-launch-environment][1331]: pam_unix(gdm-launch-environment:session): session opened for user gdm by (uid=0)
Jun 12 11:15:24 node2 polkitd[865]: Registered Authentication Agent for unix-session:c1 (system bus name :1.32 [/usr/bin/gnome-shell], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Jun 12 11:20:36 node2 sshd[2125]: Accepted publickey for ansible from 192.168.1.136 port 44260 ssh2: RSA SHA256:jpchiL+jLX3smTuII7SubLqdvcmq8e3I+5HSG4oUreQ
Jun 12 11:20:36 node2 systemd[2129]: pam_unix(systemd-user:session): session opened for user ansible by (uid=0)
Jun 12 11:20:36 node2 sshd[2125]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Jun 12 11:21:40 node2 sshd[2151]: Received disconnect from 192.168.1.136 port 44260:11: disconnected by user
Jun 12 11:21:40 node2 sshd[2151]: Disconnected from user ansible 192.168.1.136 port 44260
Jun 12 11:21:40 node2 sshd[2125]: pam_unix(sshd:session): session closed for user ansible
Jun 12 11:21:40 node2 systemd[2137]: pam_unix(systemd-user:session): session closed for user ansible
Jun 12 11:56:59 node2 sshd[2705]: Connection closed by 192.168.1.136 port 44354 [preauth]
Jun 12 11:57:52 node2 sshd[2707]: Invalid user devops from 192.168.1.136 port 44364
Jun 12 11:57:52 node2 sshd[2707]: Connection closed by invalid user devops 192.168.1.136 port 44364 [preauth]
Jun 12 11:58:14 node2 sshd[2717]: Invalid user devops from 192.168.1.136 port 44374
Jun 12 11:58:14 node2 sshd[2717]: Connection closed by invalid user devops 192.168.1.136 port 44374 [preauth]
Jun 12 12:02:29 node2 sshd[2751]: Connection closed by authenticating user ansible 192.168.1.136 port 44386 [preauth]
Jun 12 12:03:30 node2 sshd[2761]: Accepted password for ansible from 192.168.1.136 port 44400 ssh2
Jun 12 12:03:31 node2 systemd[2766]: pam_unix(systemd-user:session): session opened for user ansible by (uid=0)
Jun 12 12:03:31 node2 sshd[2761]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Jun 12 12:04:37 node2 sshd[2788]: Received disconnect from 192.168.1.136 port 44400:11: disconnected by user
Jun 12 12:04:37 node2 sshd[2788]: Disconnected from user ansible 192.168.1.136 port 44400
Jun 12 12:04:37 node2 sshd[2761]: pam_unix(sshd:session): session closed for user ansible
Jun 12 12:04:37 node2 systemd[2776]: pam_unix(systemd-user:session): session closed for user ansible
Jun 12 12:15:12 node2 sshd[3120]: Accepted password for ansible from 192.168.1.136 port 44410 ssh2
Jun 12 12:15:13 node2 systemd[3126]: pam_unix(systemd-user:session): session opened for user ansible by (uid=0)
Jun 12 12:15:13 node2 sshd[3120]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Jun 12 12:16:19 node2 sshd[3147]: Received disconnect from 192.168.1.136 port 44410:11: disconnected by user
Jun 12 12:16:19 node2 sshd[3147]: Disconnected from user ansible 192.168.1.136 port 44410
Jun 12 12:16:19 node2 sshd[3120]: pam_unix(sshd:session): session closed for user ansible
Jun 12 12:16:19 node2 systemd[3133]: pam_unix(systemd-user:session): session closed for user ansible
Jun 12 12:16:25 node2 sshd[3386]: Accepted password for ansible from 192.168.1.136 port 44418 ssh2
Jun 12 12:16:26 node2 systemd[3391]: pam_unix(systemd-user:session): session opened for user ansible by (uid=0)
Jun 12 12:16:27 node2 sshd[3386]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Jun 12 12:16:31 node2 sudo[3601]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-hdrocrmyavkxxkdeqzkniumvnvvnrtjl ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1623514587.838202-4778-187058990508600/AnsiballZ_user.py
Jun 12 12:16:31 node2 sudo[3601]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 12 12:16:31 node2 sudo[3601]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 12 12:16:32 node2 useradd[3608]: new group: name=devops, GID=2024
Jun 12 12:16:32 node2 useradd[3608]: new user: name=devops, UID=2024, GID=2024, home=/home/devops, shell=/bin/bash
Jun 12 12:16:35 node2 sudo[3601]: pam_unix(sudo:session): session closed for user root
Jun 12 12:17:35 node2 sshd[3412]: Received disconnect from 192.168.1.136 port 44418:11: disconnected by user
Jun 12 12:17:35 node2 sshd[3412]: Disconnected from user ansible 192.168.1.136 port 44418
Jun 12 12:17:35 node2 sshd[3386]: pam_unix(sshd:session): session closed for user ansible
Jun 12 12:22:52 node2 sshd[3711]: Accepted password for ansible from 192.168.1.136 port 44440 ssh2
Jun 12 12:22:53 node2 systemd[3716]: pam_unix(systemd-user:session): session opened for user ansible by (uid=0)
Jun 12 12:22:53 node2 sshd[3711]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Jun 12 12:22:59 node2 unix_chkpwd[3813]: password check failed for user (root)
Jun 12 12:22:59 node2 su[3808]: pam_unix(su-l:auth): authentication failure; logname=ansible uid=1001 euid=0 tty=pts/0 ruser=ansible rhost=  user=root
Jun 12 12:23:08 node2 su[3814]: pam_systemd(su-l:session): Cannot create session: Already running in a session or user slice
Jun 12 12:23:08 node2 su[3814]: pam_unix(su-l:session): session opened for user root by ansible(uid=1001)
Jun 12 12:24:16 node2 passwd[3865]: pam_unix(passwd:chauthtok): password changed for devops
Jun 12 12:24:16 node2 passwd[3865]: gkr-pam: couldn't update the login keyring password: no old password was entered
Jun 12 12:24:31 node2 su[3814]: pam_unix(su-l:session): session closed for user root
Jun 12 12:24:32 node2 sshd[3738]: Received disconnect from 192.168.1.136 port 44440:11: disconnected by user
Jun 12 12:24:32 node2 sshd[3738]: Disconnected from user ansible 192.168.1.136 port 44440
Jun 12 12:24:33 node2 sshd[3711]: pam_unix(sshd:session): session closed for user ansible
Jun 12 12:24:33 node2 systemd[3724]: pam_unix(systemd-user:session): session closed for user ansible
Jun 12 12:26:25 node2 sshd[3909]: Connection closed by authenticating user devops 192.168.1.136 port 44452 [preauth]
Jun 12 12:26:25 node2 sshd[3911]: Connection closed by authenticating user devops 192.168.1.136 port 44454 [preauth]
Jun 12 12:26:28 node2 sshd[3913]: Accepted password for devops from 192.168.1.136 port 44456 ssh2
Jun 12 12:26:28 node2 systemd[3918]: pam_unix(systemd-user:session): session opened for user devops by (uid=0)
Jun 12 12:26:28 node2 sshd[3913]: pam_unix(sshd:session): session opened for user devops by (uid=0)
Jun 12 12:26:29 node2 sshd[3939]: Received disconnect from 192.168.1.136 port 44456:11: disconnected by user
Jun 12 12:26:29 node2 sshd[3939]: Disconnected from user devops 192.168.1.136 port 44456
Jun 12 12:26:29 node2 sshd[3913]: pam_unix(sshd:session): session closed for user devops
Jun 12 12:26:29 node2 systemd[3925]: pam_unix(systemd-user:session): session closed for user devops
Jun 12 12:31:39 node2 sshd[4034]: Accepted publickey for devops from 192.168.1.136 port 44470 ssh2: RSA SHA256:4eU5yRUy7W0CunssYRsg6EJor1uJiMpwuo9O9cNRZ8Y
Jun 12 12:31:39 node2 systemd[4038]: pam_unix(systemd-user:session): session opened for user devops by (uid=0)
Jun 12 12:31:40 node2 sshd[4034]: pam_unix(sshd:session): session opened for user devops by (uid=0)
Jun 12 12:33:05 node2 sshd[4060]: Received disconnect from 192.168.1.136 port 44470:11: disconnected by user
Jun 12 12:33:05 node2 sshd[4060]: Disconnected from user devops 192.168.1.136 port 44470
Jun 12 12:33:05 node2 sshd[4034]: pam_unix(sshd:session): session closed for user devops
Jun 12 12:33:05 node2 systemd[4048]: pam_unix(systemd-user:session): session closed for user devops
Jun 12 12:34:23 node2 sshd[4265]: Accepted password for ansible from 192.168.1.136 port 44480 ssh2
Jun 12 12:34:24 node2 systemd[4270]: pam_unix(systemd-user:session): session opened for user ansible by (uid=0)
Jun 12 12:34:24 node2 sshd[4265]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Jun 12 12:35:26 node2 sshd[4291]: Received disconnect from 192.168.1.136 port 44480:11: disconnected by user
Jun 12 12:35:26 node2 sshd[4291]: Disconnected from user ansible 192.168.1.136 port 44480
Jun 12 12:35:26 node2 sshd[4265]: pam_unix(sshd:session): session closed for user ansible
Jun 12 12:35:26 node2 systemd[4277]: pam_unix(systemd-user:session): session closed for user ansible
Jun 12 12:43:59 node2 sshd[4496]: Accepted publickey for devops from 192.168.1.136 port 44486 ssh2: RSA SHA256:4eU5yRUy7W0CunssYRsg6EJor1uJiMpwuo9O9cNRZ8Y
Jun 12 12:44:00 node2 systemd[4500]: pam_unix(systemd-user:session): session opened for user devops by (uid=0)
Jun 12 12:44:00 node2 sshd[4496]: pam_unix(sshd:session): session opened for user devops by (uid=0)
Jun 12 12:44:05 node2 sudo[4711]:  devops : user NOT in sudoers ; TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-qjzkdbmivkhqtvlpimdxxlegwfmhqwsp ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1623516241.4692266-5974-134930499570327/AnsiballZ_stat.py
Jun 12 12:45:06 node2 sshd[4522]: Received disconnect from 192.168.1.136 port 44486:11: disconnected by user
Jun 12 12:45:06 node2 sshd[4522]: Disconnected from user devops 192.168.1.136 port 44486
Jun 12 12:45:06 node2 sshd[4496]: pam_unix(sshd:session): session closed for user devops
Jun 12 12:45:06 node2 systemd[4508]: pam_unix(systemd-user:session): session closed for user devops
Jun 12 12:48:41 node2 sshd[4802]: Accepted publickey for devops from 192.168.1.136 port 44494 ssh2: RSA SHA256:4eU5yRUy7W0CunssYRsg6EJor1uJiMpwuo9O9cNRZ8Y
Jun 12 12:48:41 node2 systemd[4806]: pam_unix(systemd-user:session): session opened for user devops by (uid=0)
Jun 12 12:48:42 node2 sshd[4802]: pam_unix(sshd:session): session opened for user devops by (uid=0)
Jun 12 12:48:47 node2 sudo[5016]:  devops : user NOT in sudoers ; TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-temwjaroaxafxabqhpkparnblqitbzco ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1623516523.203236-6144-218405321908806/AnsiballZ_stat.py
Jun 12 12:49:47 node2 sshd[4828]: Received disconnect from 192.168.1.136 port 44494:11: disconnected by user
Jun 12 12:49:47 node2 sshd[4828]: Disconnected from user devops 192.168.1.136 port 44494
Jun 12 12:49:47 node2 sshd[4802]: pam_unix(sshd:session): session closed for user devops
Jun 12 12:49:47 node2 systemd[4814]: pam_unix(systemd-user:session): session closed for user devops
Jun 12 12:57:33 node2 sshd[5135]: Accepted publickey for devops from 192.168.1.136 port 44502 ssh2: RSA SHA256:4eU5yRUy7W0CunssYRsg6EJor1uJiMpwuo9O9cNRZ8Y
Jun 12 12:57:33 node2 systemd[5140]: pam_unix(systemd-user:session): session opened for user devops by (uid=0)
Jun 12 12:57:34 node2 sshd[5135]: pam_unix(sshd:session): session opened for user devops by (uid=0)
Jun 12 12:57:39 node2 sudo[5359]:  devops : user NOT in sudoers ; TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-fvqxmxddsjnkyqlpcytpkuiceujrlsky ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1623517055.1107166-6425-227953582993851/AnsiballZ_setup.py
Jun 12 12:58:40 node2 sshd[5166]: Received disconnect from 192.168.1.136 port 44502:11: disconnected by user
Jun 12 12:58:40 node2 sshd[5166]: Disconnected from user devops 192.168.1.136 port 44502
Jun 12 12:58:40 node2 sshd[5135]: pam_unix(sshd:session): session closed for user devops
Jun 12 12:58:40 node2 systemd[5149]: pam_unix(systemd-user:session): session closed for user devops
Jun 12 12:58:42 node2 sshd[5416]: Accepted publickey for devops from 192.168.1.136 port 44510 ssh2: RSA SHA256:4eU5yRUy7W0CunssYRsg6EJor1uJiMpwuo9O9cNRZ8Y
Jun 12 12:58:43 node2 systemd[5420]: pam_unix(systemd-user:session): session opened for user devops by (uid=0)
Jun 12 12:58:44 node2 sshd[5416]: pam_unix(sshd:session): session opened for user devops by (uid=0)
Jun 12 12:58:49 node2 sudo[5630]:  devops : user NOT in sudoers ; TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-kskljdtfsxpvcgompxxlwqpzjzbutpxw ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1623517124.6616194-6513-26358263828129/AnsiballZ_setup.py
Jun 12 12:59:12 node2 sudo[5806]:  devops : user NOT in sudoers ; TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-lfqzlcoilvbzcbxpntteimojjuzniwaa ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1623517150.5131304-6614-165127848817679/AnsiballZ_setup.py
Jun 12 13:00:13 node2 sshd[5441]: Received disconnect from 192.168.1.136 port 44510:11: disconnected by user
Jun 12 13:00:13 node2 sshd[5441]: Disconnected from user devops 192.168.1.136 port 44510
Jun 12 13:00:13 node2 sshd[5416]: pam_unix(sshd:session): session closed for user devops
Jun 12 13:00:13 node2 systemd[5427]: pam_unix(systemd-user:session): session closed for user devops
Jun 12 13:03:29 node2 sshd[5885]: Accepted publickey for devops from 192.168.1.136 port 44520 ssh2: RSA SHA256:4eU5yRUy7W0CunssYRsg6EJor1uJiMpwuo9O9cNRZ8Y
Jun 12 13:03:29 node2 systemd[5889]: pam_unix(systemd-user:session): session opened for user devops by (uid=0)
Jun 12 13:03:30 node2 sshd[5885]: pam_unix(sshd:session): session opened for user devops by (uid=0)
Jun 12 13:03:35 node2 sudo[6108]:  devops : user NOT in sudoers ; TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-zmyodqkuwggvldnnvmxvbqfyxjziompy ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1623517410.910094-6790-164640922074368/AnsiballZ_lineinfile.py
Jun 12 13:04:35 node2 sshd[5911]: Received disconnect from 192.168.1.136 port 44520:11: disconnected by user
Jun 12 13:04:35 node2 sshd[5911]: Disconnected from user devops 192.168.1.136 port 44520
Jun 12 13:04:35 node2 sshd[5885]: pam_unix(sshd:session): session closed for user devops
Jun 12 13:04:35 node2 systemd[5898]: pam_unix(systemd-user:session): session closed for user devops
Jun 12 13:04:40 node2 sshd[6165]: Connection closed by authenticating user ansible 192.168.1.136 port 44526 [preauth]
Jun 12 13:05:06 node2 sshd[6167]: Accepted password for ansible from 192.168.1.136 port 44534 ssh2
Jun 12 13:05:07 node2 systemd[6172]: pam_unix(systemd-user:session): session opened for user ansible by (uid=0)
Jun 12 13:05:07 node2 sshd[6167]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Jun 12 13:05:12 node2 sudo[6382]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ggrzpmataiurrlqqdmdfuzphshgjvsdr ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1623517508.2093537-6913-243937278918256/AnsiballZ_lineinfile.py
Jun 12 13:05:12 node2 sudo[6382]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 12 13:05:12 node2 sudo[6382]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 12 13:05:13 node2 sudo[6382]: pam_unix(sudo:session): session closed for user root
Jun 12 13:06:13 node2 sshd[6193]: Received disconnect from 192.168.1.136 port 44534:11: disconnected by user
Jun 12 13:06:13 node2 sshd[6193]: Disconnected from user ansible 192.168.1.136 port 44534
Jun 12 13:06:13 node2 sshd[6167]: pam_unix(sshd:session): session closed for user ansible
Jun 12 13:06:13 node2 systemd[6182]: pam_unix(systemd-user:session): session closed for user ansible
Jun 12 13:10:13 node2 sshd[6466]: Accepted publickey for devops from 192.168.1.136 port 44544 ssh2: RSA SHA256:4eU5yRUy7W0CunssYRsg6EJor1uJiMpwuo9O9cNRZ8Y
Jun 12 13:10:13 node2 systemd[6472]: pam_unix(systemd-user:session): session opened for user devops by (uid=0)
Jun 12 13:10:14 node2 sshd[6466]: pam_unix(sshd:session): session opened for user devops by (uid=0)
Jun 12 13:11:19 node2 sshd[6493]: Received disconnect from 192.168.1.136 port 44544:11: disconnected by user
Jun 12 13:11:19 node2 sshd[6493]: Disconnected from user devops 192.168.1.136 port 44544
Jun 12 13:11:19 node2 sshd[6466]: pam_unix(sshd:session): session closed for user devops
Jun 12 13:11:19 node2 systemd[6479]: pam_unix(systemd-user:session): session closed for user devops
Jun 12 13:15:16 node2 sshd[6766]: Accepted publickey for devops from 192.168.1.136 port 44552 ssh2: RSA SHA256:4eU5yRUy7W0CunssYRsg6EJor1uJiMpwuo9O9cNRZ8Y
Jun 12 13:15:17 node2 systemd[6770]: pam_unix(systemd-user:session): session opened for user devops by (uid=0)
Jun 12 13:15:18 node2 sshd[6766]: pam_unix(sshd:session): session opened for user devops by (uid=0)
Jun 12 13:15:22 node2 sudo[6980]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-icleexjxzajloapozxrvfigcilgkzbxs ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1623518118.6435924-7274-7406788248801/AnsiballZ_stat.py
Jun 12 13:15:22 node2 sudo[6980]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 12 13:15:22 node2 sudo[6980]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jun 12 13:15:23 node2 sudo[6980]: pam_unix(sudo:session): session closed for user root
Jun 12 13:15:24 node2 sudo[7090]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-vsqvbzqxmsfwyzgmtjtwebhfncpqrgos ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1623518118.6435924-7274-7406788248801/AnsiballZ_copy.py
Jun 12 13:15:24 node2 sudo[7090]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 12 13:15:24 node2 sudo[7090]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jun 12 13:15:25 node2 sudo[7090]: pam_unix(sudo:session): session closed for user root
Jun 12 13:15:55 node2 sudo[7275]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-xdwxbvxvwyoxluormtvcexptigxuqwmi ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1623518153.416225-7388-180746714649488/AnsiballZ_stat.py
Jun 12 13:15:55 node2 sudo[7275]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 12 13:15:55 node2 sudo[7275]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jun 12 13:15:56 node2 sudo[7275]: pam_unix(sudo:session): session closed for user root
Jun 12 13:15:57 node2 sudo[7346]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-fjkvkldfcoytozkoihmtjpnmtxtttmzg ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1623518153.416225-7388-180746714649488/AnsiballZ_file.py
Jun 12 13:15:57 node2 sudo[7346]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 12 13:15:57 node2 sudo[7346]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jun 12 13:15:58 node2 sudo[7346]: pam_unix(sudo:session): session closed for user root
Jun 12 13:16:58 node2 sshd[6791]: Received disconnect from 192.168.1.136 port 44552:11: disconnected by user
Jun 12 13:16:58 node2 sshd[6791]: Disconnected from user devops 192.168.1.136 port 44552
Jun 12 13:16:58 node2 sshd[6766]: pam_unix(sshd:session): session closed for user devops
Jun 12 13:16:58 node2 systemd[6778]: pam_unix(systemd-user:session): session closed for user devops
Jun 12 13:19:40 node2 sshd[7423]: Accepted publickey for devops from 192.168.1.136 port 44562 ssh2: RSA SHA256:4eU5yRUy7W0CunssYRsg6EJor1uJiMpwuo9O9cNRZ8Y
Jun 12 13:19:41 node2 systemd[7427]: pam_unix(systemd-user:session): session opened for user devops by (uid=0)
Jun 12 13:19:41 node2 sshd[7423]: pam_unix(sshd:session): session opened for user devops by (uid=0)
Jun 12 13:20:47 node2 sshd[7448]: Received disconnect from 192.168.1.136 port 44562:11: disconnected by user
Jun 12 13:20:47 node2 sshd[7448]: Disconnected from user devops 192.168.1.136 port 44562
Jun 12 13:20:47 node2 sshd[7423]: pam_unix(sshd:session): session closed for user devops
Jun 12 13:20:47 node2 systemd[7434]: pam_unix(systemd-user:session): session closed for user devops
Jun 12 14:13:10 node2 sshd[8122]: Accepted publickey for devops from 192.168.1.136 port 44568 ssh2: RSA SHA256:4eU5yRUy7W0CunssYRsg6EJor1uJiMpwuo9O9cNRZ8Y
Jun 12 14:13:10 node2 systemd[8126]: pam_unix(systemd-user:session): session opened for user devops by (uid=0)
Jun 12 14:13:10 node2 sshd[8122]: pam_unix(sshd:session): session opened for user devops by (uid=0)
Jun 12 14:13:13 node2 sudo[8338]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-epxjmekwcgsmjahbbahcbxnnkwmyhigo ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1623521591.3557882-8646-161867579531861/AnsiballZ_setup.py
Jun 12 14:13:13 node2 sudo[8338]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 12 14:13:13 node2 sudo[8338]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jun 12 14:13:14 node2 sudo[8338]: pam_unix(sudo:session): session closed for user root
Jun 12 14:13:16 node2 sudo[8515]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-vazlwntwahjwlvdpxxyljaryogdldaxg ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1623521595.6214397-8660-3561697942851/AnsiballZ_dnf.py
Jun 12 14:13:16 node2 sudo[8515]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 12 14:13:16 node2 sudo[8515]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jun 12 14:13:20 node2 sudo[8515]: pam_unix(sudo:session): session closed for user root
Jun 12 14:13:21 node2 sudo[8648]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-vhirykzeywjaqckvuciljtmvsxdptrzw ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1623521600.6747632-8669-192907563618099/AnsiballZ_systemd.py
Jun 12 14:13:21 node2 sudo[8648]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 12 14:13:21 node2 sudo[8648]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jun 12 14:13:22 node2 sudo[8648]: pam_unix(sudo:session): session closed for user root
Jun 12 14:13:23 node2 sudo[8785]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-hwdmvmycihjvhhgfmctonxjrvrxpqtat ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1623521602.8074086-8678-116924387961142/AnsiballZ_firewalld.py
Jun 12 14:13:23 node2 sudo[8785]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 12 14:13:23 node2 sudo[8785]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jun 12 14:13:24 node2 sudo[8785]: pam_unix(sudo:session): session closed for user root
Jun 12 14:13:25 node2 sudo[8918]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-wnkacszxkndijagyjgiapyxphqbujkgj ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1623521605.0143874-8687-256386197386916/AnsiballZ_systemd.py
Jun 12 14:13:25 node2 sudo[8918]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 12 14:13:25 node2 sudo[8918]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jun 12 14:13:26 node2 sudo[8918]: pam_unix(sudo:session): session closed for user root
Jun 12 14:13:27 node2 sudo[9054]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-dmcilvftkwvfdyebmxnpgathpgwqghgd ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1623521606.68185-8696-227181382669712/AnsiballZ_systemd.py
Jun 12 14:13:27 node2 sudo[9054]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 12 14:13:27 node2 sudo[9054]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jun 12 14:13:27 node2 sudo[9054]: pam_unix(sudo:session): session closed for user root
Jun 12 14:13:28 node2 sudo[9190]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ynnoexbhkptsuuiuyjmbsncwyqzkzmkp ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1623521608.2358184-8705-164349561173651/AnsiballZ_stat.py
Jun 12 14:13:28 node2 sudo[9190]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 12 14:13:28 node2 sudo[9190]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jun 12 14:13:29 node2 sudo[9190]: pam_unix(sudo:session): session closed for user root
Jun 12 14:14:01 node2 sudo[9372]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-osdmslzoninaiinjgmzlpzfcuogwydxs ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1623521640.6012187-8818-107987826934768/AnsiballZ_setup.py
Jun 12 14:14:01 node2 sudo[9372]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 12 14:14:01 node2 sudo[9372]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jun 12 14:14:03 node2 sudo[9372]: pam_unix(sudo:session): session closed for user root
Jun 12 14:14:04 node2 sudo[9549]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-pcnsfmfkmophxsmixjfnaspchkgrnyzd ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1623521643.8982575-8829-35857611495482/AnsiballZ_dnf.py
Jun 12 14:14:04 node2 sudo[9549]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 12 14:14:04 node2 sudo[9549]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jun 12 14:14:20 node2 groupadd[9586]: group added to /etc/group: name=apache, GID=48
Jun 12 14:14:20 node2 groupadd[9586]: group added to /etc/gshadow: name=apache
Jun 12 14:14:20 node2 groupadd[9586]: new group: name=apache, GID=48
Jun 12 14:14:21 node2 useradd[9593]: new user: name=apache, UID=48, GID=48, home=/usr/share/httpd, shell=/sbin/nologin
Jun 12 14:14:24 node2 groupadd[9603]: group added to /etc/group: name=mysql, GID=27
Jun 12 14:14:24 node2 groupadd[9603]: group added to /etc/gshadow: name=mysql
Jun 12 14:14:25 node2 groupadd[9603]: new group: name=mysql, GID=27
Jun 12 14:14:25 node2 useradd[9609]: new user: name=mysql, UID=27, GID=27, home=/var/lib/mysql, shell=/sbin/nologin
Jun 12 14:14:35 node2 groupadd[9622]: group added to /etc/group: name=nginx, GID=973
Jun 12 14:14:35 node2 groupadd[9622]: group added to /etc/gshadow: name=nginx
Jun 12 14:14:35 node2 groupadd[9622]: new group: name=nginx, GID=973
Jun 12 14:14:36 node2 useradd[9629]: new user: name=nginx, UID=974, GID=973, home=/var/lib/nginx, shell=/sbin/nologin
Jun 12 14:14:45 node2 sudo[9549]: pam_unix(sudo:session): session closed for user root
Jun 12 14:14:47 node2 sudo[11175]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-zkpfzbnroqkvqhcgpbdhmyzkevwlsfzd ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1623521685.988764-8856-70863498463135/AnsiballZ_systemd.py
Jun 12 14:14:47 node2 sudo[11175]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 12 14:14:47 node2 sudo[11175]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jun 12 14:14:48 node2 sudo[11175]: pam_unix(sudo:session): session closed for user root
Jun 12 14:14:49 node2 sudo[11952]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-poepsylugpgsnjzxuroixywckkjqtuaf ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1623521688.5260828-8865-11552256055731/AnsiballZ_firewalld.py
Jun 12 14:14:49 node2 sudo[11952]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 12 14:14:49 node2 sudo[11952]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jun 12 14:14:50 node2 sudo[11952]: pam_unix(sudo:session): session closed for user root
Jun 12 14:14:51 node2 sudo[12570]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-zvjxwlwqzvfbswbmfzqcgeqghuawezeg ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1623521691.1144123-8874-91865057710232/AnsiballZ_systemd.py
Jun 12 14:14:51 node2 sudo[12570]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 12 14:14:51 node2 sudo[12570]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jun 12 14:14:53 node2 sudo[12570]: pam_unix(sudo:session): session closed for user root
Jun 12 14:14:54 node2 sudo[13384]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-wyeyzopjhbszeevcjyvoxodnxsswwqdy ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1623521694.1140242-8883-213250976291110/AnsiballZ_systemd.py
Jun 12 14:14:54 node2 sudo[13384]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 12 14:14:54 node2 sudo[13384]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jun 12 14:15:00 node2 sudo[13384]: pam_unix(sudo:session): session closed for user root
Jun 12 14:15:01 node2 sudo[16822]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-yxrmwzxtrspixsbueaulnnocmkcljrxe ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1623521700.6755419-8892-171984376244431/AnsiballZ_stat.py
Jun 12 14:15:01 node2 sudo[16822]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 12 14:15:01 node2 sudo[16822]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jun 12 14:15:01 node2 sudo[16822]: pam_unix(sudo:session): session closed for user root
Jun 12 14:15:03 node2 sudo[17538]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-fzjgkfmswexsxmnmlglvijgeomdvytha ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1623521700.6755419-8892-171984376244431/AnsiballZ_copy.py
Jun 12 14:15:03 node2 sudo[17538]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 12 14:15:03 node2 sudo[17538]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jun 12 14:15:03 node2 sudo[17538]: pam_unix(sudo:session): session closed for user root
Jun 12 14:15:35 node2 sudo[40727]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-kpigisoxnggkoblsndzzdeiymwhxvebp ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1623521733.8529253-9007-217570990363736/AnsiballZ_setup.py
Jun 12 14:15:35 node2 sudo[40727]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 12 14:15:35 node2 sudo[40727]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jun 12 14:15:36 node2 sudo[40727]: pam_unix(sudo:session): session closed for user root
Jun 12 14:15:38 node2 sudo[40912]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-uqsslwatidipswufhlfapdigezgdvxnq ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1623521737.2098367-9018-176375166271718/AnsiballZ_dnf.py
Jun 12 14:15:38 node2 sudo[40912]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 12 14:15:38 node2 sudo[40912]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jun 12 14:15:42 node2 sudo[40912]: pam_unix(sudo:session): session closed for user root
Jun 12 14:15:43 node2 sudo[41045]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ekbrseobxmdyhqfeyvaaktaxsonvrjfp ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1623521742.6003535-9031-89960306678993/AnsiballZ_systemd.py
Jun 12 14:15:43 node2 sudo[41045]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 12 14:15:43 node2 sudo[41045]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jun 12 14:15:44 node2 sudo[41045]: pam_unix(sudo:session): session closed for user root
Jun 12 14:15:45 node2 sudo[41182]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ivvajafpdcjtmzvuphtsrmjjeznlwozk ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1623521744.7016232-9042-177300187419650/AnsiballZ_firewalld.py
Jun 12 14:15:45 node2 sudo[41182]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 12 14:15:45 node2 sudo[41182]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jun 12 14:15:46 node2 sudo[41182]: pam_unix(sudo:session): session closed for user root
Jun 12 14:15:47 node2 sudo[41315]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ezqkdwaxxccjkglmyxnltagcwamcrctq ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1623521746.9358392-9051-62952334380058/AnsiballZ_systemd.py
Jun 12 14:15:47 node2 sudo[41315]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 12 14:15:47 node2 sudo[41315]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jun 12 14:15:48 node2 sudo[41315]: pam_unix(sudo:session): session closed for user root
Jun 12 14:15:49 node2 sudo[41452]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-tendynreerwwgfnyiqvrqsguwuunugyo ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1623521748.6719022-9060-140896907558545/AnsiballZ_systemd.py
Jun 12 14:15:49 node2 sudo[41452]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 12 14:15:49 node2 sudo[41452]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jun 12 14:15:50 node2 sudo[41452]: pam_unix(sudo:session): session closed for user root
Jun 12 14:15:51 node2 sudo[41589]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-scfjhcujcwdbdugaxgjilxqlmqtcthth ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1623521750.3342068-9069-189138387588785/AnsiballZ_stat.py
Jun 12 14:15:51 node2 sudo[41589]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 12 14:15:51 node2 sudo[41589]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jun 12 14:15:51 node2 sudo[41589]: pam_unix(sudo:session): session closed for user root
Jun 12 14:15:52 node2 sudo[41660]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-nigtkygbtfeoofnjbssfbtqnowsioibn ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1623521750.3342068-9069-189138387588785/AnsiballZ_file.py
Jun 12 14:15:52 node2 sudo[41660]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 12 14:15:52 node2 sudo[41660]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jun 12 14:15:52 node2 sudo[41660]: pam_unix(sudo:session): session closed for user root
Jun 12 14:16:52 node2 sshd[8148]: Received disconnect from 192.168.1.136 port 44568:11: disconnected by user
Jun 12 14:16:52 node2 sshd[8148]: Disconnected from user devops 192.168.1.136 port 44568
Jun 12 14:16:52 node2 sshd[8122]: pam_unix(sshd:session): session closed for user devops
Jun 19 11:39:27 node2 polkitd[889]: Loading rules from directory /etc/polkit-1/rules.d
Jun 19 11:39:27 node2 polkitd[889]: Loading rules from directory /usr/share/polkit-1/rules.d
Jun 19 11:39:27 node2 polkitd[889]: Finished loading, compiling and executing 10 rules
Jun 19 11:39:27 node2 polkitd[889]: Acquired the name org.freedesktop.PolicyKit1 on the system bus
Jun 19 11:39:36 node2 sshd[1067]: Server listening on 0.0.0.0 port 22.
Jun 19 11:39:36 node2 sshd[1067]: Server listening on :: port 22.
Jun 19 11:39:49 node2 systemd[1500]: pam_unix(systemd-user:session): session opened for user gdm by (uid=0)
Jun 19 11:39:51 node2 gdm-launch-environment][1476]: pam_unix(gdm-launch-environment:session): session opened for user gdm by (uid=0)
Jun 19 11:40:08 node2 polkitd[889]: Registered Authentication Agent for unix-session:c1 (system bus name :1.47 [/usr/bin/gnome-shell], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Jun 19 11:49:19 node2 systemd[2532]: pam_unix(systemd-user:session): session opened for user root by (uid=0)
Jun 19 11:49:20 node2 gdm-password][2523]: pam_unix(gdm-password:session): session opened for user root by (uid=0)
Jun 19 11:49:26 node2 polkitd[889]: Registered Authentication Agent for unix-session:2 (system bus name :1.216 [/usr/bin/gnome-shell], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Jun 19 11:59:43 node2 polkitd[890]: Loading rules from directory /etc/polkit-1/rules.d
Jun 19 11:59:43 node2 polkitd[890]: Loading rules from directory /usr/share/polkit-1/rules.d
Jun 19 11:59:43 node2 polkitd[890]: Finished loading, compiling and executing 10 rules
Jun 19 11:59:43 node2 polkitd[890]: Acquired the name org.freedesktop.PolicyKit1 on the system bus
Jun 19 11:59:48 node2 sshd[1060]: Server listening on 0.0.0.0 port 22.
Jun 19 11:59:48 node2 sshd[1060]: Server listening on :: port 22.
Jun 19 11:59:54 node2 systemd[1480]: pam_unix(systemd-user:session): session opened for user gdm by (uid=0)
Jun 19 11:59:55 node2 gdm-launch-environment][1453]: pam_unix(gdm-launch-environment:session): session opened for user gdm by (uid=0)
Jun 19 12:00:07 node2 polkitd[890]: Registered Authentication Agent for unix-session:c1 (system bus name :1.46 [/usr/bin/gnome-shell], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Jun 19 12:13:50 node2 systemd[2557]: pam_unix(systemd-user:session): session opened for user root by (uid=0)
Jun 19 12:13:51 node2 gdm-password][2548]: pam_unix(gdm-password:session): session opened for user root by (uid=0)
Jun 19 12:13:54 node2 polkitd[890]: Registered Authentication Agent for unix-session:2 (system bus name :1.231 [/usr/bin/gnome-shell], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Jun 19 16:11:19 node2 sshd[6765]: Accepted publickey for ansible from 192.168.2.179 port 55926 ssh2: RSA SHA256:jpchiL+jLX3smTuII7SubLqdvcmq8e3I+5HSG4oUreQ
Jun 19 16:11:20 node2 systemd[6769]: pam_unix(systemd-user:session): session opened for user ansible by (uid=0)
Jun 19 16:11:21 node2 sshd[6765]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Jun 23 17:58:34 node2 polkitd[878]: Loading rules from directory /etc/polkit-1/rules.d
Jun 23 17:58:34 node2 polkitd[878]: Loading rules from directory /usr/share/polkit-1/rules.d
Jun 23 17:58:34 node2 polkitd[878]: Finished loading, compiling and executing 10 rules
Jun 23 17:58:34 node2 polkitd[878]: Acquired the name org.freedesktop.PolicyKit1 on the system bus
Jun 23 17:58:41 node2 sshd[1068]: Server listening on 0.0.0.0 port 22.
Jun 23 17:58:41 node2 sshd[1068]: Server listening on :: port 22.
Jun 23 17:58:52 node2 systemd[1480]: pam_unix(systemd-user:session): session opened for user gdm by (uid=0)
Jun 23 17:58:53 node2 gdm-launch-environment][1452]: pam_unix(gdm-launch-environment:session): session opened for user gdm by (uid=0)
Jun 23 17:59:08 node2 polkitd[878]: Registered Authentication Agent for unix-session:c1 (system bus name :1.47 [/usr/bin/gnome-shell], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Jun 23 18:28:20 node2 systemd[2698]: pam_unix(systemd-user:session): session opened for user root by (uid=0)
Jun 23 18:28:20 node2 gdm-password][2689]: pam_unix(gdm-password:session): session opened for user root by (uid=0)
Jun 23 18:28:24 node2 polkitd[878]: Registered Authentication Agent for unix-session:2 (system bus name :1.232 [/usr/bin/gnome-shell], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Jun 23 18:31:38 node2 polkitd[890]: Loading rules from directory /etc/polkit-1/rules.d
Jun 23 18:31:38 node2 polkitd[890]: Loading rules from directory /usr/share/polkit-1/rules.d
Jun 23 18:31:38 node2 polkitd[890]: Finished loading, compiling and executing 10 rules
Jun 23 18:31:38 node2 polkitd[890]: Acquired the name org.freedesktop.PolicyKit1 on the system bus
Jun 23 18:31:42 node2 sshd[1061]: Server listening on 0.0.0.0 port 22.
Jun 23 18:31:42 node2 sshd[1061]: Server listening on :: port 22.
Jun 23 18:31:48 node2 systemd[1483]: pam_unix(systemd-user:session): session opened for user gdm by (uid=0)
Jun 23 18:31:48 node2 gdm-launch-environment][1457]: pam_unix(gdm-launch-environment:session): session opened for user gdm by (uid=0)
Jun 23 18:32:00 node2 polkitd[890]: Registered Authentication Agent for unix-session:c1 (system bus name :1.48 [/usr/bin/gnome-shell], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Jun 23 18:35:08 node2 systemd[2463]: pam_unix(systemd-user:session): session opened for user root by (uid=0)
Jun 23 18:35:08 node2 gdm-password][2453]: pam_unix(gdm-password:session): session opened for user root by (uid=0)
Jun 23 18:35:12 node2 polkitd[890]: Registered Authentication Agent for unix-session:2 (system bus name :1.230 [/usr/bin/gnome-shell], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Jun 23 18:57:22 node2 sshd[3465]: Accepted publickey for ansible from 192.168.1.136 port 43862 ssh2: RSA SHA256:jpchiL+jLX3smTuII7SubLqdvcmq8e3I+5HSG4oUreQ
Jun 23 18:57:23 node2 systemd[3469]: pam_unix(systemd-user:session): session opened for user ansible by (uid=0)
Jun 23 18:57:23 node2 sshd[3465]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Jun 23 18:58:27 node2 sshd[3491]: Received disconnect from 192.168.1.136 port 43862:11: disconnected by user
Jun 23 18:58:27 node2 sshd[3491]: Disconnected from user ansible 192.168.1.136 port 43862
Jun 23 18:58:27 node2 sshd[3465]: pam_unix(sshd:session): session closed for user ansible
Jun 23 20:23:05 node2 sshd[4991]: Accepted publickey for ansible from 192.168.1.136 port 43866 ssh2: RSA SHA256:jpchiL+jLX3smTuII7SubLqdvcmq8e3I+5HSG4oUreQ
Jun 23 20:23:05 node2 systemd[4996]: pam_unix(systemd-user:session): session opened for user ansible by (uid=0)
Jun 23 20:23:06 node2 sshd[4991]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Jun 23 20:23:10 node2 sudo[5207]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-onlgcaxawngafzxihblbxqhcrdlnnrui ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624494186.9240737-4071-14015753189370/AnsiballZ_setup.py
Jun 23 20:23:10 node2 sudo[5207]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 23 20:23:10 node2 sudo[5207]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 23 20:23:12 node2 sudo[5207]: pam_unix(sudo:session): session closed for user root
Jun 23 20:24:12 node2 sshd[5017]: Received disconnect from 192.168.1.136 port 43866:11: disconnected by user
Jun 23 20:24:12 node2 sshd[5017]: Disconnected from user ansible 192.168.1.136 port 43866
Jun 23 20:24:12 node2 sshd[4991]: pam_unix(sshd:session): session closed for user ansible
Jun 23 20:24:12 node2 systemd[5004]: pam_unix(systemd-user:session): session closed for user ansible
Jun 23 20:24:58 node2 sshd[5324]: Accepted publickey for ansible from 192.168.1.136 port 43878 ssh2: RSA SHA256:jpchiL+jLX3smTuII7SubLqdvcmq8e3I+5HSG4oUreQ
Jun 23 20:24:59 node2 systemd[5328]: pam_unix(systemd-user:session): session opened for user ansible by (uid=0)
Jun 23 20:24:59 node2 sshd[5324]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Jun 23 20:25:03 node2 sudo[5538]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-pnlgcliijdvlhwpbmqngbzidbofvhvty ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624494300.1867695-4161-16546281301800/AnsiballZ_setup.py
Jun 23 20:25:03 node2 sudo[5538]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 23 20:25:03 node2 sudo[5538]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 23 20:25:05 node2 sudo[5538]: pam_unix(sudo:session): session closed for user root
Jun 23 20:25:13 node2 sudo[5715]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-lnwuhyfmimeeimgrtyyybxzknvssbvzn ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624494312.6805573-4217-45573802024446/AnsiballZ_dnf.py
Jun 23 20:25:13 node2 sudo[5715]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 23 20:25:13 node2 sudo[5715]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 23 20:27:27 node2 sudo[5715]: pam_unix(sudo:session): session closed for user root
Jun 23 20:28:22 node2 sudo[5922]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-lumcwlwgmpkhpqipgivcfibicqmziyse ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624494500.2363088-4280-259299580261925/AnsiballZ_systemd.py
Jun 23 20:28:22 node2 sudo[5922]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 23 20:28:22 node2 sudo[5922]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 23 20:28:23 node2 sudo[5922]: pam_unix(sudo:session): session closed for user root
Jun 23 20:28:27 node2 sudo[6059]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-trkjntilbekbtxzpqbdxjtgshkimxonf ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624494506.7295551-4318-67761065426852/AnsiballZ_systemd.py
Jun 23 20:28:27 node2 sudo[6059]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 23 20:28:27 node2 sudo[6059]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 23 20:28:28 node2 sudo[6059]: pam_unix(sudo:session): session closed for user root
Jun 23 20:28:31 node2 sudo[6196]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-vtpkmywqhwggzmxwnzeuntpicjreyuug ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624494509.9820487-4355-66513247840998/AnsiballZ_stat.py
Jun 23 20:28:31 node2 sudo[6196]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 23 20:28:31 node2 sudo[6196]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 23 20:28:31 node2 sudo[6196]: pam_unix(sudo:session): session closed for user root
Jun 23 20:28:33 node2 sudo[6304]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-mubhzrenmmpyfjzcmmkiozzrjdnccvei ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624494509.9820487-4355-66513247840998/AnsiballZ_copy.py
Jun 23 20:28:33 node2 sudo[6304]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 23 20:28:33 node2 sudo[6304]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 23 20:28:34 node2 sudo[6304]: pam_unix(sudo:session): session closed for user root
Jun 23 20:28:36 node2 sudo[6441]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-vpgcscuuzkqtbbpqyefadjlttojtzyqt ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624494515.0934422-4419-92793729643788/AnsiballZ_firewalld.py
Jun 23 20:28:36 node2 sudo[6441]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 23 20:28:36 node2 sudo[6441]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 23 20:28:39 node2 sudo[6441]: pam_unix(sudo:session): session closed for user root
Jun 23 20:29:39 node2 sshd[5349]: Received disconnect from 192.168.1.136 port 43878:11: disconnected by user
Jun 23 20:29:39 node2 sshd[5349]: Disconnected from user ansible 192.168.1.136 port 43878
Jun 23 20:29:39 node2 sshd[5324]: pam_unix(sshd:session): session closed for user ansible
Jun 23 20:29:39 node2 systemd[5336]: pam_unix(systemd-user:session): session closed for user ansible
Jun 23 20:40:58 node2 sshd[6670]: Accepted publickey for ansible from 192.168.1.136 port 43888 ssh2: RSA SHA256:jpchiL+jLX3smTuII7SubLqdvcmq8e3I+5HSG4oUreQ
Jun 23 20:40:59 node2 systemd[6674]: pam_unix(systemd-user:session): session opened for user ansible by (uid=0)
Jun 23 20:40:59 node2 sshd[6670]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Jun 23 20:41:03 node2 sudo[6885]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-aeilimbkcdjmuzqcxhuqhtyyarbvuena ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624495260.4565077-4656-60911897942208/AnsiballZ_setup.py
Jun 23 20:41:03 node2 sudo[6885]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 23 20:41:03 node2 sudo[6885]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 23 20:41:05 node2 sudo[6885]: pam_unix(sudo:session): session closed for user root
Jun 23 20:41:14 node2 sudo[7062]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-tfcqnmfwjkcdksufwyhydhgjijswkzzp ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624495273.4524758-4712-202641766438369/AnsiballZ_dnf.py
Jun 23 20:41:14 node2 sudo[7062]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 23 20:41:14 node2 sudo[7062]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 23 20:41:28 node2 sudo[7062]: pam_unix(sudo:session): session closed for user root
Jun 23 20:41:50 node2 sudo[23330]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-cpxehudnhbbbkcqeydzlbjsgpwdndvux ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624495308.335167-4756-98569417388788/AnsiballZ_systemd.py
Jun 23 20:41:50 node2 sudo[23330]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 23 20:41:50 node2 sudo[23330]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 23 20:41:51 node2 sudo[23330]: pam_unix(sudo:session): session closed for user root
Jun 23 20:41:52 node2 sudo[24249]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-bmdwpamxxwdcwpusntpwzyxrplbtskuj ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624495311.8950872-4792-216051247850068/AnsiballZ_systemd.py
Jun 23 20:41:52 node2 sudo[24249]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 23 20:41:52 node2 sudo[24249]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 23 20:41:53 node2 sudo[24249]: pam_unix(sudo:session): session closed for user root
Jun 23 20:41:55 node2 sudo[25442]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-fpadoeipiphebqcuweuihmryrsszmnuy ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624495314.3280337-4829-260176919473154/AnsiballZ_stat.py
Jun 23 20:41:55 node2 sudo[25442]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 23 20:41:55 node2 sudo[25442]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 23 20:41:55 node2 sudo[25442]: pam_unix(sudo:session): session closed for user root
Jun 23 20:41:56 node2 sudo[25982]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-tqxtzcvsgncyehytotlbtcycycbvabzw ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624495314.3280337-4829-260176919473154/AnsiballZ_file.py
Jun 23 20:41:56 node2 sudo[25982]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 23 20:41:56 node2 sudo[25982]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 23 20:41:57 node2 sudo[25982]: pam_unix(sudo:session): session closed for user root
Jun 23 20:41:58 node2 sudo[26933]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-gojsabccnjlmquvdpmmrbxqwaciflbcm ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624495317.6938932-4881-271776104182000/AnsiballZ_firewalld.py
Jun 23 20:41:58 node2 sudo[26933]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 23 20:41:58 node2 sudo[26933]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 23 20:41:59 node2 sudo[26933]: pam_unix(sudo:session): session closed for user root
Jun 23 20:43:00 node2 sshd[6696]: Received disconnect from 192.168.1.136 port 43888:11: disconnected by user
Jun 23 20:43:00 node2 sshd[6696]: Disconnected from user ansible 192.168.1.136 port 43888
Jun 23 20:43:00 node2 sshd[6670]: pam_unix(sshd:session): session closed for user ansible
Jun 23 20:43:00 node2 systemd[6684]: pam_unix(systemd-user:session): session closed for user ansible
Jun 23 20:44:33 node2 sshd[37321]: Accepted publickey for ansible from 192.168.1.136 port 43896 ssh2: RSA SHA256:jpchiL+jLX3smTuII7SubLqdvcmq8e3I+5HSG4oUreQ
Jun 23 20:44:34 node2 systemd[37325]: pam_unix(systemd-user:session): session opened for user ansible by (uid=0)
Jun 23 20:44:34 node2 sshd[37321]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Jun 23 20:45:41 node2 sshd[37346]: Received disconnect from 192.168.1.136 port 43896:11: disconnected by user
Jun 23 20:45:41 node2 sshd[37346]: Disconnected from user ansible 192.168.1.136 port 43896
Jun 23 20:45:41 node2 sshd[37321]: pam_unix(sshd:session): session closed for user ansible
Jun 23 20:45:41 node2 systemd[37332]: pam_unix(systemd-user:session): session closed for user ansible
Jun 23 21:13:42 node2 sshd[38007]: Accepted publickey for ansible from 192.168.1.136 port 43908 ssh2: RSA SHA256:jpchiL+jLX3smTuII7SubLqdvcmq8e3I+5HSG4oUreQ
Jun 23 21:13:43 node2 systemd[38012]: pam_unix(systemd-user:session): session opened for user ansible by (uid=0)
Jun 23 21:13:43 node2 sshd[38007]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Jun 23 21:13:48 node2 sudo[38230]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-tezgeefuhuotrrgdwxtuneaomyqbsbpp ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624497224.6904178-5435-25364373694090/AnsiballZ_setup.py
Jun 23 21:13:48 node2 sudo[38230]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 23 21:13:48 node2 sudo[38230]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 23 21:13:51 node2 sudo[38230]: pam_unix(sudo:session): session closed for user root
Jun 23 21:13:57 node2 sudo[38408]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-fzcadwalvpkxedwtmkcdjvzmylzsjkir ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624497236.286359-5513-193339908013256/AnsiballZ_user.py
Jun 23 21:13:57 node2 sudo[38408]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 23 21:13:57 node2 sudo[38408]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 23 21:13:58 node2 useradd[38415]: new group: name=oracle, GID=2025
Jun 23 21:13:58 node2 useradd[38415]: new user: name=oracle, UID=2025, GID=2025, home=/home/oracle, shell=/bin/bash
Jun 23 21:14:00 node2 sudo[38408]: pam_unix(sudo:session): session closed for user root
Jun 23 21:15:01 node2 sshd[38042]: Received disconnect from 192.168.1.136 port 43908:11: disconnected by user
Jun 23 21:15:01 node2 sshd[38042]: Disconnected from user ansible 192.168.1.136 port 43908
Jun 23 21:15:01 node2 sshd[38007]: pam_unix(sshd:session): session closed for user ansible
Jun 23 21:20:56 node2 sshd[38561]: Accepted publickey for ansible from 192.168.1.136 port 43922 ssh2: RSA SHA256:jpchiL+jLX3smTuII7SubLqdvcmq8e3I+5HSG4oUreQ
Jun 23 21:20:57 node2 systemd[38565]: pam_unix(systemd-user:session): session opened for user ansible by (uid=0)
Jun 23 21:20:57 node2 sshd[38561]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Jun 23 21:22:03 node2 sshd[38588]: Received disconnect from 192.168.1.136 port 43922:11: disconnected by user
Jun 23 21:22:03 node2 sshd[38588]: Disconnected from user ansible 192.168.1.136 port 43922
Jun 23 21:22:03 node2 sshd[38561]: pam_unix(sshd:session): session closed for user ansible
Jun 23 21:22:03 node2 systemd[38574]: pam_unix(systemd-user:session): session closed for user ansible
Jun 23 21:26:13 node2 sshd[38891]: Accepted publickey for ansible from 192.168.1.136 port 43928 ssh2: RSA SHA256:jpchiL+jLX3smTuII7SubLqdvcmq8e3I+5HSG4oUreQ
Jun 23 21:26:14 node2 systemd[38895]: pam_unix(systemd-user:session): session opened for user ansible by (uid=0)
Jun 23 21:26:15 node2 sshd[38891]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Jun 23 21:26:19 node2 sudo[39108]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-oueougsvuyzcsjqyfaxhnpaxmsgblzzk ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624497975.7859402-5774-271654522175242/AnsiballZ_setup.py
Jun 23 21:26:19 node2 sudo[39108]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 23 21:26:19 node2 sudo[39108]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 23 21:26:22 node2 sudo[39108]: pam_unix(sudo:session): session closed for user root
Jun 23 21:26:28 node2 sudo[39285]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-jpfnrlgwhgcxuthuhcynmvpxjpxqeoqn ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624497987.2339118-5844-247162326352576/AnsiballZ_user.py
Jun 23 21:26:28 node2 sudo[39285]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 23 21:26:28 node2 sudo[39285]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 23 21:26:29 node2 sudo[39285]: pam_unix(sudo:session): session closed for user root
Jun 23 21:27:29 node2 sshd[38917]: Received disconnect from 192.168.1.136 port 43928:11: disconnected by user
Jun 23 21:27:29 node2 sshd[38917]: Disconnected from user ansible 192.168.1.136 port 43928
Jun 23 21:27:29 node2 sshd[38891]: pam_unix(sshd:session): session closed for user ansible
Jun 23 21:27:29 node2 systemd[38903]: pam_unix(systemd-user:session): session closed for user ansible
Jun 23 21:30:26 node2 sshd[39390]: Accepted publickey for ansible from 192.168.1.136 port 43940 ssh2: RSA SHA256:jpchiL+jLX3smTuII7SubLqdvcmq8e3I+5HSG4oUreQ
Jun 23 21:30:27 node2 systemd[39394]: pam_unix(systemd-user:session): session opened for user ansible by (uid=0)
Jun 23 21:30:27 node2 sshd[39390]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Jun 23 21:30:32 node2 sudo[39604]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-xawqgujfghmqszpjexeetbdhqehkngxu ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624498228.6853456-5947-148272898566703/AnsiballZ_setup.py
Jun 23 21:30:32 node2 sudo[39604]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 23 21:30:32 node2 sudo[39604]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 23 21:30:34 node2 sudo[39604]: pam_unix(sudo:session): session closed for user root
Jun 23 21:30:41 node2 sudo[39785]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-wetumdfnigupsfquxdraghcublhkidkw ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624498240.1379454-6017-151722399683000/AnsiballZ_user.py
Jun 23 21:30:41 node2 sudo[39785]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 23 21:30:41 node2 sudo[39785]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 23 21:30:42 node2 sudo[39785]: pam_unix(sudo:session): session closed for user root
Jun 23 21:31:42 node2 sshd[39415]: Received disconnect from 192.168.1.136 port 43940:11: disconnected by user
Jun 23 21:31:42 node2 sshd[39415]: Disconnected from user ansible 192.168.1.136 port 43940
Jun 23 21:31:42 node2 sshd[39390]: pam_unix(sshd:session): session closed for user ansible
Jun 23 21:31:42 node2 systemd[39401]: pam_unix(systemd-user:session): session closed for user ansible
Jun 23 21:33:58 node2 sshd[39883]: Accepted publickey for ansible from 192.168.1.136 port 43946 ssh2: RSA SHA256:jpchiL+jLX3smTuII7SubLqdvcmq8e3I+5HSG4oUreQ
Jun 23 21:33:59 node2 systemd[39887]: pam_unix(systemd-user:session): session opened for user ansible by (uid=0)
Jun 23 21:33:59 node2 sshd[39883]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Jun 23 21:35:03 node2 sshd[39908]: Received disconnect from 192.168.1.136 port 43946:11: disconnected by user
Jun 23 21:35:03 node2 sshd[39908]: Disconnected from user ansible 192.168.1.136 port 43946
Jun 23 21:35:03 node2 sshd[39883]: pam_unix(sshd:session): session closed for user ansible
Jun 23 21:35:03 node2 systemd[39894]: pam_unix(systemd-user:session): session closed for user ansible
Jun 23 21:38:23 node2 sshd[40239]: Accepted publickey for ansible from 192.168.1.136 port 43948 ssh2: RSA SHA256:jpchiL+jLX3smTuII7SubLqdvcmq8e3I+5HSG4oUreQ
Jun 23 21:38:24 node2 systemd[40243]: pam_unix(systemd-user:session): session opened for user ansible by (uid=0)
Jun 23 21:38:24 node2 sshd[40239]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Jun 23 21:39:27 node2 sshd[40264]: Received disconnect from 192.168.1.136 port 43948:11: disconnected by user
Jun 23 21:39:27 node2 sshd[40264]: Disconnected from user ansible 192.168.1.136 port 43948
Jun 23 21:39:27 node2 sshd[40239]: pam_unix(sshd:session): session closed for user ansible
Jun 23 21:39:28 node2 systemd[40250]: pam_unix(systemd-user:session): session closed for user ansible
Jun 24 06:43:50 node2 sshd[48433]: Accepted publickey for ansible from 192.168.1.136 port 44066 ssh2: RSA SHA256:jpchiL+jLX3smTuII7SubLqdvcmq8e3I+5HSG4oUreQ
Jun 24 06:43:50 node2 systemd[48437]: pam_unix(systemd-user:session): session opened for user ansible by (uid=0)
Jun 24 06:43:51 node2 sshd[48433]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Jun 24 06:45:00 node2 sshd[48460]: Received disconnect from 192.168.1.136 port 44066:11: disconnected by user
Jun 24 06:45:00 node2 sshd[48460]: Disconnected from user ansible 192.168.1.136 port 44066
Jun 24 06:45:00 node2 sshd[48433]: pam_unix(sshd:session): session closed for user ansible
Jun 24 06:45:00 node2 systemd[48447]: pam_unix(systemd-user:session): session closed for user ansible
Jun 24 06:46:59 node2 sshd[48908]: Accepted publickey for ansible from 192.168.1.136 port 44072 ssh2: RSA SHA256:jpchiL+jLX3smTuII7SubLqdvcmq8e3I+5HSG4oUreQ
Jun 24 06:46:59 node2 systemd[48912]: pam_unix(systemd-user:session): session opened for user ansible by (uid=0)
Jun 24 06:47:00 node2 sshd[48908]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Jun 24 06:48:10 node2 sshd[48933]: Received disconnect from 192.168.1.136 port 44072:11: disconnected by user
Jun 24 06:48:10 node2 sshd[48933]: Disconnected from user ansible 192.168.1.136 port 44072
Jun 24 06:48:10 node2 sshd[48908]: pam_unix(sshd:session): session closed for user ansible
Jun 24 06:48:10 node2 systemd[48919]: pam_unix(systemd-user:session): session closed for user ansible
Jun 24 07:30:27 node2 sshd[49959]: Accepted publickey for ansible from 192.168.1.136 port 44114 ssh2: RSA SHA256:jpchiL+jLX3smTuII7SubLqdvcmq8e3I+5HSG4oUreQ
Jun 24 07:30:27 node2 systemd[49963]: pam_unix(systemd-user:session): session opened for user ansible by (uid=0)
Jun 24 07:30:28 node2 sshd[49959]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Jun 24 07:30:31 node2 sudo[50174]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-nhpjmyxzybuczwxwurfdmbzybojwhsqk ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624534228.6101635-12137-63297834388059/AnsiballZ_setup.py
Jun 24 07:30:31 node2 sudo[50174]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 24 07:30:31 node2 sudo[50174]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 24 07:30:32 node2 sudo[50174]: pam_unix(sudo:session): session closed for user root
Jun 24 07:30:37 node2 sudo[50351]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-akdgpgtgbhecaujphgimxwuzvdlzmwcv ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624534236.9488692-12209-19043824202921/AnsiballZ_file.py
Jun 24 07:30:37 node2 sudo[50351]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 24 07:30:37 node2 sudo[50351]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 24 07:30:38 node2 sudo[50351]: pam_unix(sudo:session): session closed for user root
Jun 24 07:31:40 node2 sshd[49984]: Received disconnect from 192.168.1.136 port 44114:11: disconnected by user
Jun 24 07:31:40 node2 sshd[49984]: Disconnected from user ansible 192.168.1.136 port 44114
Jun 24 07:31:40 node2 sshd[49959]: pam_unix(sshd:session): session closed for user ansible
Jun 24 07:31:40 node2 systemd[49970]: pam_unix(systemd-user:session): session closed for user ansible
Jun 24 07:33:13 node2 sshd[50500]: Accepted publickey for ansible from 192.168.1.136 port 44124 ssh2: RSA SHA256:jpchiL+jLX3smTuII7SubLqdvcmq8e3I+5HSG4oUreQ
Jun 24 07:33:13 node2 systemd[50504]: pam_unix(systemd-user:session): session opened for user ansible by (uid=0)
Jun 24 07:33:13 node2 sshd[50500]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Jun 24 07:33:16 node2 sudo[50716]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-wrxckcunbxjyuxyaktivjmbvkuxspwts ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624534394.2636943-12312-200024582955597/AnsiballZ_setup.py
Jun 24 07:33:16 node2 sudo[50716]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 24 07:33:16 node2 sudo[50716]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 24 07:33:18 node2 sudo[50716]: pam_unix(sudo:session): session closed for user root
Jun 24 07:33:22 node2 sudo[50895]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-rnnniynrfquaodpndlpfbigfarezagjf ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624534402.1527367-12383-103142225587043/AnsiballZ_file.py
Jun 24 07:33:22 node2 sudo[50895]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 24 07:33:22 node2 sudo[50895]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 24 07:33:23 node2 sudo[50895]: pam_unix(sudo:session): session closed for user root
Jun 24 07:33:26 node2 sudo[51028]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ezcokvypxtomjjxgfmtcvytwywzhykae ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624534405.3359573-12428-81038668097822/AnsiballZ_stat.py
Jun 24 07:33:26 node2 sudo[51028]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 24 07:33:26 node2 sudo[51028]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 24 07:33:26 node2 sudo[51028]: pam_unix(sudo:session): session closed for user root
Jun 24 07:33:27 node2 sudo[51136]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-cupnygdgrgdrlsvmfdjtbhveecdqnbff ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624534405.3359573-12428-81038668097822/AnsiballZ_copy.py
Jun 24 07:33:27 node2 sudo[51136]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 24 07:33:27 node2 sudo[51136]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 24 07:33:28 node2 sudo[51136]: pam_unix(sudo:session): session closed for user root
Jun 24 07:33:47 node2 sudo[51312]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-rxmxdabmdtwkvyweblewcukhluzfucov ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624534425.901318-12516-224651593856391/AnsiballZ_setup.py
Jun 24 07:33:47 node2 sudo[51312]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 24 07:33:47 node2 sudo[51312]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 24 07:33:48 node2 sudo[51312]: pam_unix(sudo:session): session closed for user root
Jun 24 07:33:50 node2 sudo[51489]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-vqnddkmzazpolbmhgpkyzrzpanltdvrv ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624534429.3809662-12573-6190721721021/AnsiballZ_file.py
Jun 24 07:33:50 node2 sudo[51489]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 24 07:33:50 node2 sudo[51489]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 24 07:33:50 node2 sudo[51489]: pam_unix(sudo:session): session closed for user root
Jun 24 07:33:52 node2 sudo[51622]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-lhlktksyvrpgdznircebflvoccbfeele ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624534431.0307324-12618-239888192295212/AnsiballZ_stat.py
Jun 24 07:33:52 node2 sudo[51622]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 24 07:33:52 node2 sudo[51622]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 24 07:33:52 node2 sudo[51622]: pam_unix(sudo:session): session closed for user root
Jun 24 07:33:53 node2 sudo[51693]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-bqepzejaeichgfyowmitqewigovkayxy ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624534431.0307324-12618-239888192295212/AnsiballZ_file.py
Jun 24 07:33:53 node2 sudo[51693]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 24 07:33:53 node2 sudo[51693]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 24 07:33:53 node2 sudo[51693]: pam_unix(sudo:session): session closed for user root
Jun 24 07:34:53 node2 sshd[50525]: Received disconnect from 192.168.1.136 port 44124:11: disconnected by user
Jun 24 07:34:53 node2 sshd[50525]: Disconnected from user ansible 192.168.1.136 port 44124
Jun 24 07:34:53 node2 sshd[50500]: pam_unix(sshd:session): session closed for user ansible
Jun 24 07:34:53 node2 systemd[50511]: pam_unix(systemd-user:session): session closed for user ansible
Jun 24 07:35:34 node2 sshd[51765]: Accepted publickey for ansible from 192.168.1.136 port 44134 ssh2: RSA SHA256:jpchiL+jLX3smTuII7SubLqdvcmq8e3I+5HSG4oUreQ
Jun 24 07:35:35 node2 systemd[51769]: pam_unix(systemd-user:session): session opened for user ansible by (uid=0)
Jun 24 07:35:35 node2 sshd[51765]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Jun 24 07:35:49 node2 sudo[52151]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-zcrjzitrdfyelapbxslrauhqtxhwegov ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624534548.547845-12789-26218099456593/AnsiballZ_command.py
Jun 24 07:35:49 node2 sudo[52151]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 24 07:35:49 node2 sudo[52151]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 24 07:35:50 node2 sudo[52151]: pam_unix(sudo:session): session closed for user root
Jun 24 07:36:50 node2 sshd[51790]: Received disconnect from 192.168.1.136 port 44134:11: disconnected by user
Jun 24 07:36:50 node2 sshd[51790]: Disconnected from user ansible 192.168.1.136 port 44134
Jun 24 07:36:50 node2 sshd[51765]: pam_unix(sshd:session): session closed for user ansible
Jun 24 07:36:50 node2 systemd[51776]: pam_unix(systemd-user:session): session closed for user ansible
Jun 24 07:43:47 node2 sshd[52313]: Accepted publickey for ansible from 192.168.1.136 port 44144 ssh2: RSA SHA256:jpchiL+jLX3smTuII7SubLqdvcmq8e3I+5HSG4oUreQ
Jun 24 07:43:48 node2 systemd[52317]: pam_unix(systemd-user:session): session opened for user ansible by (uid=0)
Jun 24 07:43:48 node2 sshd[52313]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Jun 24 07:43:51 node2 sudo[52529]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-iosvirsxvwkolnnrarqmxyqxwkodxctn ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624535029.1922889-12940-128229165675454/AnsiballZ_setup.py
Jun 24 07:43:51 node2 sudo[52529]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 24 07:43:51 node2 sudo[52529]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 24 07:43:52 node2 sudo[52529]: pam_unix(sudo:session): session closed for user root
Jun 24 07:43:59 node2 sudo[52708]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ouvkiuwcoemroshkyciuotuoxbtdnobp ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624535038.4199433-13010-279579293549760/AnsiballZ_dnf.py
Jun 24 07:43:59 node2 sudo[52708]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 24 07:43:59 node2 sudo[52708]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 24 07:44:02 node2 sudo[52708]: pam_unix(sudo:session): session closed for user root
Jun 24 07:44:11 node2 sudo[52849]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-axbbnikkoakpuhqllvtdeugnlnqqbaom ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624535050.358035-13063-169555411160369/AnsiballZ_systemd.py
Jun 24 07:44:11 node2 sudo[52849]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 24 07:44:11 node2 sudo[52849]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 24 07:44:11 node2 sudo[52849]: pam_unix(sudo:session): session closed for user root
Jun 24 07:45:12 node2 sshd[52340]: Received disconnect from 192.168.1.136 port 44144:11: disconnected by user
Jun 24 07:45:12 node2 sshd[52340]: Disconnected from user ansible 192.168.1.136 port 44144
Jun 24 07:45:12 node2 sshd[52313]: pam_unix(sshd:session): session closed for user ansible
Jun 24 07:45:12 node2 systemd[52327]: pam_unix(systemd-user:session): session closed for user ansible
Jun 24 07:56:46 node2 sshd[53073]: Accepted publickey for ansible from 192.168.1.136 port 44154 ssh2: RSA SHA256:jpchiL+jLX3smTuII7SubLqdvcmq8e3I+5HSG4oUreQ
Jun 24 07:56:46 node2 systemd[53077]: pam_unix(systemd-user:session): session opened for user ansible by (uid=0)
Jun 24 07:56:47 node2 sshd[53073]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Jun 24 07:56:50 node2 sudo[53289]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-laucvsekhzjtrtjczbfnsosuphtywxzv ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624535807.5714438-13237-55083312963251/AnsiballZ_setup.py
Jun 24 07:56:50 node2 sudo[53289]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 24 07:56:50 node2 sudo[53289]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 24 07:56:51 node2 sudo[53289]: pam_unix(sudo:session): session closed for user root
Jun 24 07:56:58 node2 sudo[53468]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-dafpaxdwygngnlplctbbfacdjwbajzuc ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624535817.4504507-13307-24779117663084/AnsiballZ_dnf.py
Jun 24 07:56:58 node2 sudo[53468]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 24 07:56:58 node2 sudo[53468]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 24 07:57:01 node2 sudo[53468]: pam_unix(sudo:session): session closed for user root
Jun 24 07:57:08 node2 sudo[53601]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-owtfquknhdguphexhyfircufidnvvcaj ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624535827.9288535-13351-207995596103566/AnsiballZ_systemd.py
Jun 24 07:57:08 node2 sudo[53601]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 24 07:57:08 node2 sudo[53601]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 24 07:57:09 node2 sudo[53601]: pam_unix(sudo:session): session closed for user root
Jun 24 07:57:10 node2 sudo[53738]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ipwpngncbttsiysbxhdeuiggtifinhpn ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624535829.8843358-13387-278441790314604/AnsiballZ_lineinfile.py
Jun 24 07:57:10 node2 sudo[53738]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 24 07:57:10 node2 sudo[53738]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 24 07:57:10 node2 sudo[53738]: pam_unix(sudo:session): session closed for user root
Jun 24 07:57:11 node2 sudo[53879]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-jzlakmqurlurqkjyuwnklfhdlhvctfft ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624535831.3217638-13431-20353087503866/AnsiballZ_systemd.py
Jun 24 07:57:11 node2 sudo[53879]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 24 07:57:11 node2 sudo[53879]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 24 07:57:13 node2 sudo[53879]: pam_unix(sudo:session): session closed for user root
Jun 24 07:57:26 node2 sudo[54281]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-tlsskjgsbdstsngtuvkmxqcvdetbcvxx ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624535845.550089-13476-56064559800163/AnsiballZ_setup.py
Jun 24 07:57:26 node2 sudo[54281]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 24 07:57:26 node2 sudo[54281]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 24 07:57:28 node2 sudo[54281]: pam_unix(sudo:session): session closed for user root
Jun 24 07:57:31 node2 sudo[54458]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-dvxhqlgjdxzoudymfpvmonksimhtlivn ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624535850.235953-13531-24256023023675/AnsiballZ_dnf.py
Jun 24 07:57:31 node2 sudo[54458]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 24 07:57:31 node2 sudo[54458]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 24 07:57:33 node2 sudo[54458]: pam_unix(sudo:session): session closed for user root
Jun 24 07:57:36 node2 sudo[54591]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-qydoxssnwlbxbxlgymvzfepwojhwibnc ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624535855.0706549-13575-158189782642388/AnsiballZ_systemd.py
Jun 24 07:57:36 node2 sudo[54591]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 24 07:57:36 node2 sudo[54591]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 24 07:57:36 node2 sudo[54591]: pam_unix(sudo:session): session closed for user root
Jun 24 07:57:37 node2 sudo[54728]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-awzurerkadpnjhxqjzskwekspupilnjp ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624535856.9457917-13611-192545899689432/AnsiballZ_lineinfile.py
Jun 24 07:57:37 node2 sudo[54728]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 24 07:57:37 node2 sudo[54728]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 24 07:57:37 node2 sudo[54728]: pam_unix(sudo:session): session closed for user root
Jun 24 07:58:38 node2 sshd[53099]: Received disconnect from 192.168.1.136 port 44154:11: disconnected by user
Jun 24 07:58:38 node2 sshd[53099]: Disconnected from user ansible 192.168.1.136 port 44154
Jun 24 07:58:38 node2 sshd[53073]: pam_unix(sshd:session): session closed for user ansible
Jun 24 07:58:38 node2 systemd[53084]: pam_unix(systemd-user:session): session closed for user ansible
Jun 24 08:12:10 node2 sshd[54976]: Accepted publickey for ansible from 192.168.1.136 port 44164 ssh2: RSA SHA256:jpchiL+jLX3smTuII7SubLqdvcmq8e3I+5HSG4oUreQ
Jun 24 08:12:10 node2 systemd[54980]: pam_unix(systemd-user:session): session opened for user ansible by (uid=0)
Jun 24 08:12:11 node2 sshd[54976]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Jun 24 08:12:14 node2 sudo[55199]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-rdnriyinmmxbzcbcxkkujwywgbggdlgu ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624536731.8209898-13830-206647759230887/AnsiballZ_setup.py
Jun 24 08:12:14 node2 sudo[55199]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 24 08:12:14 node2 sudo[55199]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 24 08:12:15 node2 sudo[55199]: pam_unix(sudo:session): session closed for user root
Jun 24 08:12:23 node2 sudo[55381]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-yonfqwuslzhhioykmyihjoucptbincwj ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624536742.6032927-13908-180981077689688/AnsiballZ_dnf.py
Jun 24 08:12:23 node2 sudo[55381]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 24 08:12:23 node2 sudo[55381]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 24 08:12:26 node2 sudo[55381]: pam_unix(sudo:session): session closed for user root
Jun 24 08:12:33 node2 sudo[55514]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-bpdxqoscuzlbpeovnmqwvzmebwdavmrv ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624536752.146474-13953-213671530611257/AnsiballZ_systemd.py
Jun 24 08:12:33 node2 sudo[55514]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 24 08:12:33 node2 sudo[55514]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 24 08:12:33 node2 sudo[55514]: pam_unix(sudo:session): session closed for user root
Jun 24 08:12:34 node2 sudo[55651]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-rjwtbwvxjjrgcssskgrxykvkuvfnbalu ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624536754.0710886-13989-218716979057522/AnsiballZ_lineinfile.py
Jun 24 08:12:34 node2 sudo[55651]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 24 08:12:34 node2 sudo[55651]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 24 08:12:35 node2 sudo[55651]: pam_unix(sudo:session): session closed for user root
Jun 24 08:13:35 node2 sshd[55002]: Received disconnect from 192.168.1.136 port 44164:11: disconnected by user
Jun 24 08:13:35 node2 sshd[55002]: Disconnected from user ansible 192.168.1.136 port 44164
Jun 24 08:13:35 node2 sshd[54976]: pam_unix(sshd:session): session closed for user ansible
Jun 24 08:13:35 node2 systemd[54989]: pam_unix(systemd-user:session): session closed for user ansible
Jun 24 08:28:29 node2 sshd[55922]: Accepted publickey for ansible from 192.168.1.136 port 44174 ssh2: RSA SHA256:jpchiL+jLX3smTuII7SubLqdvcmq8e3I+5HSG4oUreQ
Jun 24 08:28:29 node2 systemd[55926]: pam_unix(systemd-user:session): session opened for user ansible by (uid=0)
Jun 24 08:28:29 node2 sshd[55922]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Jun 24 08:28:32 node2 sudo[56137]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-jldoxrcelueunvjzeqkxwljrkezopxnm ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624537710.4410496-14213-133873584704579/AnsiballZ_setup.py
Jun 24 08:28:32 node2 sudo[56137]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 24 08:28:32 node2 sudo[56137]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 24 08:28:34 node2 sudo[56137]: pam_unix(sudo:session): session closed for user root
Jun 24 08:28:39 node2 sudo[56314]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ohtflqlqiokddgzmlxybbzgvfzvpajiy ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624537719.025016-14283-22438563462060/AnsiballZ_user.py
Jun 24 08:28:39 node2 sudo[56314]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 24 08:28:39 node2 sudo[56314]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 24 08:28:40 node2 sudo[56314]: pam_unix(sudo:session): session closed for user root
Jun 24 08:29:14 node2 sudo[56501]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-qcjywxevsaxwfwblzggrrkknppqdvwwp ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624537753.5627623-14346-128101147585039/AnsiballZ_setup.py
Jun 24 08:29:14 node2 sudo[56501]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 24 08:29:14 node2 sudo[56501]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 24 08:29:16 node2 sudo[56501]: pam_unix(sudo:session): session closed for user root
Jun 24 08:29:18 node2 sudo[56678]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-dnfczarzardrjuccwnzvdcvkwkigtxyh ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624537757.3063135-14401-149591696891395/AnsiballZ_user.py
Jun 24 08:29:18 node2 sudo[56678]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 24 08:29:18 node2 sudo[56678]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 24 08:29:18 node2 useradd[56685]: new group: name=stanislas, GID=2026
Jun 24 08:29:18 node2 useradd[56685]: new user: name=stanislas, UID=2026, GID=2026, home=/home/stanislas, shell=/bin/bash
Jun 24 08:29:20 node2 sudo[56678]: pam_unix(sudo:session): session closed for user root
Jun 24 08:29:28 node2 sudo[56865]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-onzkorntmbiogdkjqecmbvgewuhjpzgi ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624537767.2271845-14455-68633926486350/AnsiballZ_setup.py
Jun 24 08:29:28 node2 sudo[56865]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 24 08:29:28 node2 sudo[56865]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 24 08:29:29 node2 sudo[56865]: pam_unix(sudo:session): session closed for user root
Jun 24 08:29:31 node2 sudo[57042]: ansible : TTY=pts/1 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-zocsymmshnembogkhsusuibvqocrpiwr ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624537770.9349985-14510-182300224062356/AnsiballZ_user.py
Jun 24 08:29:31 node2 sudo[57042]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 24 08:29:31 node2 sudo[57042]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 24 08:29:32 node2 sudo[57042]: pam_unix(sudo:session): session closed for user root
Jun 24 08:30:30 node2 sshd[57256]: Accepted password for stanislas from 192.168.1.136 port 44180 ssh2
Jun 24 08:30:31 node2 systemd[57261]: pam_unix(systemd-user:session): session opened for user stanislas by (uid=0)
Jun 24 08:30:31 node2 sshd[57256]: pam_unix(sshd:session): session opened for user stanislas by (uid=0)
Jun 24 08:30:40 node2 sshd[57285]: Received disconnect from 192.168.1.136 port 44180:11: disconnected by user
Jun 24 08:30:40 node2 sshd[57285]: Disconnected from user stanislas 192.168.1.136 port 44180
Jun 24 08:30:40 node2 sshd[57256]: pam_unix(sshd:session): session closed for user stanislas
Jun 24 08:30:40 node2 systemd[57271]: pam_unix(systemd-user:session): session closed for user stanislas
Jun 24 08:30:55 node2 sshd[55947]: Received disconnect from 192.168.1.136 port 44174:11: disconnected by user
Jun 24 08:30:55 node2 sshd[55947]: Disconnected from user ansible 192.168.1.136 port 44174
Jun 24 08:30:55 node2 sshd[55922]: pam_unix(sshd:session): session closed for user ansible
Jun 24 08:57:22 node2 sshd[57785]: Accepted publickey for ansible from 192.168.1.136 port 44186 ssh2: RSA SHA256:jpchiL+jLX3smTuII7SubLqdvcmq8e3I+5HSG4oUreQ
Jun 24 08:57:23 node2 systemd[57789]: pam_unix(systemd-user:session): session opened for user ansible by (uid=0)
Jun 24 08:57:23 node2 sshd[57785]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Jun 24 08:58:27 node2 sshd[57812]: Received disconnect from 192.168.1.136 port 44186:11: disconnected by user
Jun 24 08:58:27 node2 sshd[57812]: Disconnected from user ansible 192.168.1.136 port 44186
Jun 24 08:58:27 node2 sshd[57785]: pam_unix(sshd:session): session closed for user ansible
Jun 24 08:58:27 node2 systemd[57797]: pam_unix(systemd-user:session): session closed for user ansible
Jun 26 11:09:54 node2 polkitd[864]: Loading rules from directory /etc/polkit-1/rules.d
Jun 26 11:09:54 node2 polkitd[864]: Loading rules from directory /usr/share/polkit-1/rules.d
Jun 26 11:09:54 node2 polkitd[864]: Finished loading, compiling and executing 10 rules
Jun 26 11:09:54 node2 polkitd[864]: Acquired the name org.freedesktop.PolicyKit1 on the system bus
Jun 26 11:10:04 node2 sshd[1047]: Server listening on 0.0.0.0 port 22.
Jun 26 11:10:04 node2 sshd[1047]: Server listening on :: port 22.
Jun 26 11:10:18 node2 systemd[1477]: pam_unix(systemd-user:session): session opened for user gdm by (uid=0)
Jun 26 11:10:20 node2 gdm-launch-environment][1448]: pam_unix(gdm-launch-environment:session): session opened for user gdm by (uid=0)
Jun 26 11:10:38 node2 polkitd[864]: Registered Authentication Agent for unix-session:c1 (system bus name :1.47 [/usr/bin/gnome-shell], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Jun 26 11:26:50 node2 sshd[2563]: Accepted publickey for ansible from 192.168.1.136 port 56152 ssh2: RSA SHA256:jpchiL+jLX3smTuII7SubLqdvcmq8e3I+5HSG4oUreQ
Jun 26 11:26:51 node2 systemd[2568]: pam_unix(systemd-user:session): session opened for user ansible by (uid=0)
Jun 26 11:26:51 node2 sshd[2563]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Jun 26 11:27:57 node2 sshd[2590]: Received disconnect from 192.168.1.136 port 56152:11: disconnected by user
Jun 26 11:27:57 node2 sshd[2590]: Disconnected from user ansible 192.168.1.136 port 56152
Jun 26 11:27:57 node2 sshd[2563]: pam_unix(sshd:session): session closed for user ansible
Jun 26 11:27:57 node2 systemd[2575]: pam_unix(systemd-user:session): session closed for user ansible
Jun 26 13:03:21 node2 sshd[3628]: Accepted publickey for ansible from 192.168.1.136 port 56178 ssh2: RSA SHA256:jpchiL+jLX3smTuII7SubLqdvcmq8e3I+5HSG4oUreQ
Jun 26 13:03:21 node2 systemd[3632]: pam_unix(systemd-user:session): session opened for user ansible by (uid=0)
Jun 26 13:03:21 node2 sshd[3628]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Jun 26 13:03:24 node2 sudo[3844]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-vjrlcsiantrwmzwwzcodbsqaakxqntkj ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1624727002.3202295-5777-15842388457998/AnsiballZ_command.py
Jun 26 13:03:24 node2 sudo[3844]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jun 26 13:03:24 node2 sudo[3844]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Jun 26 13:03:24 node2 sudo[3844]: pam_unix(sudo:session): session closed for user root
Jun 26 13:04:24 node2 sshd[3654]: Received disconnect from 192.168.1.136 port 56178:11: disconnected by user
Jun 26 13:04:24 node2 sshd[3654]: Disconnected from user ansible 192.168.1.136 port 56178
Jun 26 13:04:24 node2 sshd[3628]: pam_unix(sshd:session): session closed for user ansible
Jun 26 13:04:25 node2 systemd[3640]: pam_unix(systemd-user:session): session closed for user ansible
Jul  3 10:59:15 node2 polkitd[884]: Loading rules from directory /etc/polkit-1/rules.d
Jul  3 10:59:15 node2 polkitd[884]: Loading rules from directory /usr/share/polkit-1/rules.d
Jul  3 10:59:15 node2 polkitd[884]: Finished loading, compiling and executing 10 rules
Jul  3 10:59:15 node2 polkitd[884]: Acquired the name org.freedesktop.PolicyKit1 on the system bus
Jul  3 10:59:24 node2 sshd[1057]: Server listening on 0.0.0.0 port 22.
Jul  3 10:59:24 node2 sshd[1057]: Server listening on :: port 22.
Jul  3 10:59:38 node2 systemd[1497]: pam_unix(systemd-user:session): session opened for user gdm by (uid=0)
Jul  3 10:59:39 node2 gdm-launch-environment][1465]: pam_unix(gdm-launch-environment:session): session opened for user gdm by (uid=0)
Jul  3 10:59:55 node2 polkitd[884]: Registered Authentication Agent for unix-session:c1 (system bus name :1.47 [/usr/bin/gnome-shell], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Jul  3 11:10:20 node2 systemd[2542]: pam_unix(systemd-user:session): session opened for user root by (uid=0)
Jul  3 11:10:20 node2 gdm-password][2532]: pam_unix(gdm-password:session): session opened for user root by (uid=0)
Jul  3 11:10:25 node2 polkitd[884]: Registered Authentication Agent for unix-session:2 (system bus name :1.232 [/usr/bin/gnome-shell], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Jul  3 11:18:03 node2 polkitd[876]: Loading rules from directory /etc/polkit-1/rules.d
Jul  3 11:18:03 node2 polkitd[876]: Loading rules from directory /usr/share/polkit-1/rules.d
Jul  3 11:18:03 node2 polkitd[876]: Finished loading, compiling and executing 10 rules
Jul  3 11:18:03 node2 polkitd[876]: Acquired the name org.freedesktop.PolicyKit1 on the system bus
Jul  3 11:18:10 node2 sshd[1051]: Server listening on 0.0.0.0 port 22.
Jul  3 11:18:10 node2 sshd[1051]: Server listening on :: port 22.
Jul  3 11:18:18 node2 systemd[1475]: pam_unix(systemd-user:session): session opened for user gdm by (uid=0)
Jul  3 11:18:19 node2 gdm-launch-environment][1450]: pam_unix(gdm-launch-environment:session): session opened for user gdm by (uid=0)
Jul  3 11:18:34 node2 polkitd[876]: Registered Authentication Agent for unix-session:c1 (system bus name :1.46 [/usr/bin/gnome-shell], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Jul  3 11:30:40 node2 sshd[2518]: Accepted publickey for devops from 192.168.2.179 port 47414 ssh2: RSA SHA256:4eU5yRUy7W0CunssYRsg6EJor1uJiMpwuo9O9cNRZ8Y
Jul  3 11:30:41 node2 systemd[2523]: pam_unix(systemd-user:session): session opened for user devops by (uid=0)
Jul  3 11:30:41 node2 sshd[2518]: pam_unix(sshd:session): session opened for user devops by (uid=0)
Jul  3 11:32:51 node2 sshd[2545]: Received disconnect from 192.168.2.179 port 47414:11: disconnected by user
Jul  3 11:32:51 node2 sshd[2545]: Disconnected from user devops 192.168.2.179 port 47414
Jul  3 11:32:51 node2 sshd[2518]: pam_unix(sshd:session): session closed for user devops
Jul  3 11:32:51 node2 systemd[2531]: pam_unix(systemd-user:session): session closed for user devops
Jul  3 11:58:31 node2 sshd[3353]: Accepted publickey for devops from 192.168.2.179 port 47416 ssh2: RSA SHA256:4eU5yRUy7W0CunssYRsg6EJor1uJiMpwuo9O9cNRZ8Y
Jul  3 11:58:31 node2 systemd[3357]: pam_unix(systemd-user:session): session opened for user devops by (uid=0)
Jul  3 11:58:31 node2 sshd[3353]: pam_unix(sshd:session): session opened for user devops by (uid=0)
Jul  3 11:59:35 node2 sshd[3379]: Received disconnect from 192.168.2.179 port 47416:11: disconnected by user
Jul  3 11:59:35 node2 sshd[3379]: Disconnected from user devops 192.168.2.179 port 47416
Jul  3 11:59:35 node2 sshd[3353]: pam_unix(sshd:session): session closed for user devops
Jul  3 11:59:35 node2 systemd[3364]: pam_unix(systemd-user:session): session closed for user devops
Jul  3 12:03:00 node2 sshd[3685]: Accepted publickey for devops from 192.168.2.179 port 47418 ssh2: RSA SHA256:4eU5yRUy7W0CunssYRsg6EJor1uJiMpwuo9O9cNRZ8Y
Jul  3 12:03:00 node2 systemd[3689]: pam_unix(systemd-user:session): session opened for user devops by (uid=0)
Jul  3 12:03:00 node2 sshd[3685]: pam_unix(sshd:session): session opened for user devops by (uid=0)
Jul  3 12:04:04 node2 sshd[3710]: Received disconnect from 192.168.2.179 port 47418:11: disconnected by user
Jul  3 12:04:04 node2 sshd[3710]: Disconnected from user devops 192.168.2.179 port 47418
Jul  3 12:04:04 node2 sshd[3685]: pam_unix(sshd:session): session closed for user devops
Jul  3 12:04:04 node2 systemd[3696]: pam_unix(systemd-user:session): session closed for user devops
Jul  3 12:04:06 node2 sshd[3999]: Accepted publickey for devops from 192.168.2.179 port 47420 ssh2: RSA SHA256:4eU5yRUy7W0CunssYRsg6EJor1uJiMpwuo9O9cNRZ8Y
Jul  3 12:04:06 node2 systemd[4003]: pam_unix(systemd-user:session): session opened for user devops by (uid=0)
Jul  3 12:04:06 node2 sshd[3999]: pam_unix(sshd:session): session opened for user devops by (uid=0)
Jul  3 12:05:10 node2 sshd[4024]: Received disconnect from 192.168.2.179 port 47420:11: disconnected by user
Jul  3 12:05:10 node2 sshd[4024]: Disconnected from user devops 192.168.2.179 port 47420
Jul  3 12:05:10 node2 sshd[3999]: pam_unix(sshd:session): session closed for user devops
Jul  3 12:05:10 node2 systemd[4010]: pam_unix(systemd-user:session): session closed for user devops
Jul  3 13:09:21 node2 sshd[4839]: Accepted publickey for devops from 192.168.2.179 port 47422 ssh2: RSA SHA256:4eU5yRUy7W0CunssYRsg6EJor1uJiMpwuo9O9cNRZ8Y
Jul  3 13:09:21 node2 systemd[4843]: pam_unix(systemd-user:session): session opened for user devops by (uid=0)
Jul  3 13:09:22 node2 sshd[4839]: pam_unix(sshd:session): session opened for user devops by (uid=0)
Jul  3 13:09:24 node2 sudo[5055]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-krhtxyxkphxdfgmthmyjdohorhyvgeji ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1625332162.513144-5726-195262766959536/AnsiballZ_setup.py
Jul  3 13:09:24 node2 sudo[5055]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jul  3 13:09:24 node2 sudo[5055]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jul  3 13:09:25 node2 sudo[5055]: pam_unix(sudo:session): session closed for user root
Jul  3 13:09:27 node2 sudo[5232]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-qchymwivgcplttichttfgiohpyfdlxig ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1625332166.414766-5740-44043562608757/AnsiballZ_dnf.py
Jul  3 13:09:27 node2 sudo[5232]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jul  3 13:09:27 node2 sudo[5232]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jul  3 13:09:51 node2 sudo[5232]: pam_unix(sudo:session): session closed for user root
Jul  3 13:09:52 node2 sudo[6256]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ipsnbrlbbzjigshpydvelfbmjeugzabe ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1625332191.6168885-5768-151070599223075/AnsiballZ_stat.py
Jul  3 13:09:52 node2 sudo[6256]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jul  3 13:09:52 node2 sudo[6256]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jul  3 13:09:52 node2 sudo[6256]: pam_unix(sudo:session): session closed for user root
Jul  3 13:09:53 node2 sudo[6735]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-vudovlmiwyxbamzxgkxybflhxdeefsks ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1625332191.6168885-5768-151070599223075/AnsiballZ_copy.py
Jul  3 13:09:53 node2 sudo[6735]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jul  3 13:09:53 node2 sudo[6735]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jul  3 13:09:54 node2 sudo[6735]: pam_unix(sudo:session): session closed for user root
Jul  3 13:09:55 node2 sudo[7769]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-tbpebuppxbdjtbzpxstokqssdwppudea ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1625332194.403214-5784-147449025396963/AnsiballZ_systemd.py
Jul  3 13:09:55 node2 sudo[7769]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jul  3 13:09:55 node2 sudo[7769]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jul  3 13:09:56 node2 sudo[7769]: pam_unix(sudo:session): session closed for user root
Jul  3 13:09:56 node2 sudo[8155]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-uqaxxlytbybcmcliabbitopdanvfxljv ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1625332196.429838-5784-246761691062932/AnsiballZ_systemd.py
Jul  3 13:09:56 node2 sudo[8155]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jul  3 13:09:56 node2 sudo[8155]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jul  3 13:09:57 node2 sudo[8155]: pam_unix(sudo:session): session closed for user root
Jul  3 13:09:58 node2 sudo[8923]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-yuwesqkdojznfsyfxbmhqlzeqkfzfaoc ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1625332197.9633338-5800-76381032247349/AnsiballZ_firewalld.py
Jul  3 13:09:58 node2 sudo[8923]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jul  3 13:09:58 node2 sudo[8923]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jul  3 13:09:59 node2 sudo[8923]: pam_unix(sudo:session): session closed for user root
Jul  3 13:10:59 node2 sshd[4865]: Received disconnect from 192.168.2.179 port 47422:11: disconnected by user
Jul  3 13:10:59 node2 sshd[4865]: Disconnected from user devops 192.168.2.179 port 47422
Jul  3 13:10:59 node2 sshd[4839]: pam_unix(sshd:session): session closed for user devops
Jul  3 13:10:59 node2 systemd[4851]: pam_unix(systemd-user:session): session closed for user devops
Jul  3 13:14:03 node2 sshd[35652]: Accepted publickey for devops from 192.168.2.179 port 47426 ssh2: RSA SHA256:4eU5yRUy7W0CunssYRsg6EJor1uJiMpwuo9O9cNRZ8Y
Jul  3 13:14:03 node2 systemd[35656]: pam_unix(systemd-user:session): session opened for user devops by (uid=0)
Jul  3 13:14:03 node2 sshd[35652]: pam_unix(sshd:session): session opened for user devops by (uid=0)
Jul  3 13:14:06 node2 sudo[35866]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-xlhnscjdpjslzdnwoxdmajrcbfevcpdt ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1625332444.2646656-5970-151703327435606/AnsiballZ_setup.py
Jul  3 13:14:06 node2 sudo[35866]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jul  3 13:14:06 node2 sudo[35866]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jul  3 13:14:07 node2 sudo[35866]: pam_unix(sudo:session): session closed for user root
Jul  3 13:14:08 node2 sudo[36051]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ecelsovkwtemvwcacotwlnvlomwvxljm ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1625332448.1526182-5984-164822870515693/AnsiballZ_dnf.py
Jul  3 13:14:08 node2 sudo[36051]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jul  3 13:14:08 node2 sudo[36051]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jul  3 13:14:12 node2 sudo[36051]: pam_unix(sudo:session): session closed for user root
Jul  3 13:14:13 node2 sudo[36184]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ymorilfjnqvrumnlraemcrfjokbffxvb ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1625332452.377178-5993-193469354796607/AnsiballZ_stat.py
Jul  3 13:14:13 node2 sudo[36184]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jul  3 13:14:13 node2 sudo[36184]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jul  3 13:14:13 node2 sudo[36184]: pam_unix(sudo:session): session closed for user root
Jul  3 13:14:14 node2 sudo[36255]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ajlvejwvtnhuxurjbelvxjrvdvktahas ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1625332452.377178-5993-193469354796607/AnsiballZ_file.py
Jul  3 13:14:14 node2 sudo[36255]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jul  3 13:14:14 node2 sudo[36255]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jul  3 13:14:14 node2 sudo[36255]: pam_unix(sudo:session): session closed for user root
Jul  3 13:14:15 node2 sudo[36388]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-pfobocfaanxgqxfpexqkpvvkhhxdbgmf ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1625332454.8088071-6006-272139614973907/AnsiballZ_systemd.py
Jul  3 13:14:15 node2 sudo[36388]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jul  3 13:14:15 node2 sudo[36388]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jul  3 13:14:16 node2 sudo[36388]: pam_unix(sudo:session): session closed for user root
Jul  3 13:14:17 node2 sudo[36525]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-zvabvnjhrjscugkndmablrfqiskqldzi ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1625332456.6095684-6006-61257641755477/AnsiballZ_systemd.py
Jul  3 13:14:17 node2 sudo[36525]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jul  3 13:14:17 node2 sudo[36525]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jul  3 13:14:17 node2 sudo[36525]: pam_unix(sudo:session): session closed for user root
Jul  3 13:14:18 node2 sudo[36662]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-nfmelnqswdfsiiexojszpcleiclhobnt ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1625332458.0405488-6022-7537514214807/AnsiballZ_firewalld.py
Jul  3 13:14:18 node2 sudo[36662]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jul  3 13:14:18 node2 sudo[36662]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jul  3 13:14:19 node2 sudo[36662]: pam_unix(sudo:session): session closed for user root
Jul  3 13:15:19 node2 sshd[35677]: Received disconnect from 192.168.2.179 port 47426:11: disconnected by user
Jul  3 13:15:19 node2 sshd[35677]: Disconnected from user devops 192.168.2.179 port 47426
Jul  3 13:15:19 node2 sshd[35652]: pam_unix(sshd:session): session closed for user devops
Jul  3 13:15:19 node2 systemd[35662]: pam_unix(systemd-user:session): session closed for user devops
Jul  3 13:17:41 node2 sshd[36729]: Accepted publickey for devops from 192.168.2.179 port 47430 ssh2: RSA SHA256:4eU5yRUy7W0CunssYRsg6EJor1uJiMpwuo9O9cNRZ8Y
Jul  3 13:17:41 node2 systemd[36733]: pam_unix(systemd-user:session): session opened for user devops by (uid=0)
Jul  3 13:17:42 node2 sshd[36729]: pam_unix(sshd:session): session opened for user devops by (uid=0)
Jul  3 13:17:45 node2 sudo[36944]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-kgehguaaezvzgudhinosglhjlxndsvef ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1625332663.4892297-6174-142884789122686/AnsiballZ_setup.py
Jul  3 13:17:45 node2 sudo[36944]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jul  3 13:17:45 node2 sudo[36944]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jul  3 13:17:46 node2 sudo[36944]: pam_unix(sudo:session): session closed for user root
Jul  3 13:17:47 node2 sudo[37121]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-dspdeobptdhnbpgsqravmwlaxgrczgtg ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1625332666.972907-6196-154651731603984/AnsiballZ_dnf.py
Jul  3 13:17:47 node2 sudo[37121]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jul  3 13:17:47 node2 sudo[37121]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jul  3 13:17:50 node2 sudo[37121]: pam_unix(sudo:session): session closed for user root
Jul  3 13:17:51 node2 sudo[37254]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ajaqjciihhvjatpsafnylatbabtwijkl ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1625332671.1284397-6215-206070293672009/AnsiballZ_stat.py
Jul  3 13:17:51 node2 sudo[37254]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jul  3 13:17:51 node2 sudo[37254]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jul  3 13:17:52 node2 sudo[37254]: pam_unix(sudo:session): session closed for user root
Jul  3 13:17:52 node2 sudo[37325]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ivbauejwttmyotcpnczbwnabrnjfzazu ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1625332671.1284397-6215-206070293672009/AnsiballZ_file.py
Jul  3 13:17:52 node2 sudo[37325]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jul  3 13:17:52 node2 sudo[37325]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jul  3 13:17:53 node2 sudo[37325]: pam_unix(sudo:session): session closed for user root
Jul  3 13:17:54 node2 sudo[37458]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-lvvahyuyppadwqjleoxgecwwokchtats ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1625332673.7197266-6228-166322696249156/AnsiballZ_systemd.py
Jul  3 13:17:54 node2 sudo[37458]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jul  3 13:17:54 node2 sudo[37458]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jul  3 13:17:55 node2 sudo[37458]: pam_unix(sudo:session): session closed for user root
Jul  3 13:17:56 node2 sudo[37595]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-haumgtbsgomdfleysgdxalvnwdlmlnod ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1625332675.6112401-6228-94800457497077/AnsiballZ_systemd.py
Jul  3 13:17:56 node2 sudo[37595]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jul  3 13:17:56 node2 sudo[37595]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jul  3 13:17:56 node2 sudo[37595]: pam_unix(sudo:session): session closed for user root
Jul  3 13:17:57 node2 sudo[37732]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-xrmdljcmgrijtvwwoozkulhjewdjlntb ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1625332677.1314268-6244-15931792660167/AnsiballZ_firewalld.py
Jul  3 13:17:57 node2 sudo[37732]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jul  3 13:17:57 node2 sudo[37732]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jul  3 13:17:58 node2 sudo[37732]: pam_unix(sudo:session): session closed for user root
Jul  3 13:18:58 node2 sshd[36754]: Received disconnect from 192.168.2.179 port 47430:11: disconnected by user
Jul  3 13:18:58 node2 sshd[36754]: Disconnected from user devops 192.168.2.179 port 47430
Jul  3 13:18:58 node2 sshd[36729]: pam_unix(sshd:session): session closed for user devops
Jul  3 13:18:59 node2 systemd[36740]: pam_unix(systemd-user:session): session closed for user devops
Jul  3 13:21:33 node2 sshd[37809]: Accepted publickey for devops from 192.168.2.179 port 47436 ssh2: RSA SHA256:4eU5yRUy7W0CunssYRsg6EJor1uJiMpwuo9O9cNRZ8Y
Jul  3 13:21:34 node2 systemd[37813]: pam_unix(systemd-user:session): session opened for user devops by (uid=0)
Jul  3 13:21:34 node2 sshd[37809]: pam_unix(sshd:session): session opened for user devops by (uid=0)
Jul  3 13:22:51 node2 sudo[37937]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/yum remove httpd
Jul  3 13:22:51 node2 sudo[37937]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jul  3 13:22:51 node2 sudo[37937]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jul  3 13:23:00 node2 sudo[37937]: pam_unix(sudo:session): session closed for user root
Jul  3 13:23:04 node2 sshd[37834]: Received disconnect from 192.168.2.179 port 47436:11: disconnected by user
Jul  3 13:23:04 node2 sshd[37834]: Disconnected from user devops 192.168.2.179 port 47436
Jul  3 13:23:04 node2 sshd[37809]: pam_unix(sshd:session): session closed for user devops
Jul  3 13:23:05 node2 systemd[37820]: pam_unix(systemd-user:session): session closed for user devops
Jul  3 13:23:13 node2 sshd[38445]: Accepted publickey for devops from 192.168.2.179 port 47438 ssh2: RSA SHA256:4eU5yRUy7W0CunssYRsg6EJor1uJiMpwuo9O9cNRZ8Y
Jul  3 13:23:13 node2 systemd[38449]: pam_unix(systemd-user:session): session opened for user devops by (uid=0)
Jul  3 13:23:14 node2 sshd[38445]: pam_unix(sshd:session): session opened for user devops by (uid=0)
Jul  3 13:23:16 node2 sudo[38659]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-wvhrgogyenztindbhrmkbiqwxcqbtdxw ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1625332994.4509482-6447-98380996813842/AnsiballZ_setup.py
Jul  3 13:23:16 node2 sudo[38659]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jul  3 13:23:16 node2 sudo[38659]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jul  3 13:23:17 node2 sudo[38659]: pam_unix(sudo:session): session closed for user root
Jul  3 13:23:19 node2 sudo[38836]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-gckbglyhlhrjwyfyktntkbpojefcovps ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1625332998.3460476-6461-156073397406274/AnsiballZ_dnf.py
Jul  3 13:23:19 node2 sudo[38836]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jul  3 13:23:19 node2 sudo[38836]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jul  3 13:23:28 node2 sudo[38836]: pam_unix(sudo:session): session closed for user root
Jul  3 13:23:29 node2 sudo[39359]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-gztkhuklowvvvswdsfsukzjhwjxmjsta ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1625333008.5861309-6470-68424962257340/AnsiballZ_stat.py
Jul  3 13:23:29 node2 sudo[39359]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jul  3 13:23:29 node2 sudo[39359]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jul  3 13:23:29 node2 sudo[39359]: pam_unix(sudo:session): session closed for user root
Jul  3 13:23:30 node2 sudo[39565]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-jupyaxuoyizenyigzuhkyyhnhhankgqb ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1625333008.5861309-6470-68424962257340/AnsiballZ_file.py
Jul  3 13:23:30 node2 sudo[39565]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jul  3 13:23:30 node2 sudo[39565]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jul  3 13:23:30 node2 sudo[39565]: pam_unix(sudo:session): session closed for user root
Jul  3 13:23:32 node2 sudo[39700]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-yslkeghtsexhgksxouvuyzzansyltjde ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1625333011.2373264-6483-247869101926020/AnsiballZ_systemd.py
Jul  3 13:23:32 node2 sudo[39700]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jul  3 13:23:32 node2 sudo[39700]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jul  3 13:23:32 node2 sudo[39700]: pam_unix(sudo:session): session closed for user root
Jul  3 13:23:33 node2 sudo[39837]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ianpojdcsyxecobvyyuzcompgxgtrbqk ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1625333013.1181784-6483-65197212676042/AnsiballZ_systemd.py
Jul  3 13:23:33 node2 sudo[39837]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jul  3 13:23:33 node2 sudo[39837]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jul  3 13:23:36 node2 sudo[39837]: pam_unix(sudo:session): session closed for user root
Jul  3 13:23:37 node2 sudo[40222]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-krdbhtbznazinchmpinwvyrugxrybdwj ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1625333016.487883-6499-120056712897275/AnsiballZ_firewalld.py
Jul  3 13:23:37 node2 sudo[40222]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jul  3 13:23:37 node2 sudo[40222]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jul  3 13:23:38 node2 sudo[40222]: pam_unix(sudo:session): session closed for user root
Jul  3 13:24:38 node2 sshd[38470]: Received disconnect from 192.168.2.179 port 47438:11: disconnected by user
Jul  3 13:24:38 node2 sshd[38470]: Disconnected from user devops 192.168.2.179 port 47438
Jul  3 13:24:38 node2 sshd[38445]: pam_unix(sshd:session): session closed for user devops
Jul  3 13:24:38 node2 systemd[38456]: pam_unix(systemd-user:session): session closed for user devops
Jul  3 13:25:35 node2 sshd[40282]: Accepted publickey for devops from 192.168.2.179 port 47442 ssh2: RSA SHA256:4eU5yRUy7W0CunssYRsg6EJor1uJiMpwuo9O9cNRZ8Y
Jul  3 13:25:35 node2 systemd[40286]: pam_unix(systemd-user:session): session opened for user devops by (uid=0)
Jul  3 13:25:35 node2 sshd[40282]: pam_unix(sshd:session): session opened for user devops by (uid=0)
Jul  3 13:25:38 node2 sudo[40496]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-yudakdyoysypmoighzpdblwgaeaoeamo ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1625333136.1218913-6641-202137151178618/AnsiballZ_setup.py
Jul  3 13:25:38 node2 sudo[40496]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jul  3 13:25:38 node2 sudo[40496]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jul  3 13:25:39 node2 sudo[40496]: pam_unix(sudo:session): session closed for user root
Jul  3 13:25:40 node2 sudo[40673]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-mirbbqcxvlxdnsopipagbbvyavuylkgp ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1625333140.0636795-6655-212378463516850/AnsiballZ_dnf.py
Jul  3 13:25:40 node2 sudo[40673]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jul  3 13:25:40 node2 sudo[40673]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jul  3 13:25:43 node2 sudo[40673]: pam_unix(sudo:session): session closed for user root
Jul  3 13:25:44 node2 sudo[40806]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-krmqzzgldlktryrkmxwlwmudamxofeqt ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1625333144.166117-6666-147752914851884/AnsiballZ_stat.py
Jul  3 13:25:44 node2 sudo[40806]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jul  3 13:25:44 node2 sudo[40806]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jul  3 13:25:45 node2 sudo[40806]: pam_unix(sudo:session): session closed for user root
Jul  3 13:25:45 node2 sudo[40877]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-fmicziuobghvwveagktvhokaabvqbmtb ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1625333144.166117-6666-147752914851884/AnsiballZ_file.py
Jul  3 13:25:45 node2 sudo[40877]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jul  3 13:25:45 node2 sudo[40877]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jul  3 13:25:46 node2 sudo[40877]: pam_unix(sudo:session): session closed for user root
Jul  3 13:25:47 node2 sudo[41010]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-hjeqytfphfmgrkkkorfaxecrrzekmsao ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1625333146.5839493-6681-156458660981651/AnsiballZ_systemd.py
Jul  3 13:25:47 node2 sudo[41010]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jul  3 13:25:47 node2 sudo[41010]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jul  3 13:25:48 node2 sudo[41010]: pam_unix(sudo:session): session closed for user root
Jul  3 13:25:48 node2 sudo[41147]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-kgfpzqpoopanxugqlzxgecxehtakjjcw ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1625333148.386371-6681-21494771461695/AnsiballZ_systemd.py
Jul  3 13:25:48 node2 sudo[41147]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jul  3 13:25:48 node2 sudo[41147]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jul  3 13:25:49 node2 sudo[41147]: pam_unix(sudo:session): session closed for user root
Jul  3 13:25:50 node2 sudo[41284]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-eqlmfkmeequixpzgftdsmkvlgppeonwv ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1625333149.8288713-6711-84483971060530/AnsiballZ_firewalld.py
Jul  3 13:25:50 node2 sudo[41284]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jul  3 13:25:50 node2 sudo[41284]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jul  3 13:25:51 node2 sudo[41284]: pam_unix(sudo:session): session closed for user root
Jul  3 13:26:51 node2 sshd[40307]: Received disconnect from 192.168.2.179 port 47442:11: disconnected by user
Jul  3 13:26:51 node2 sshd[40307]: Disconnected from user devops 192.168.2.179 port 47442
Jul  3 13:26:51 node2 sshd[40282]: pam_unix(sshd:session): session closed for user devops
Jul  3 13:26:51 node2 systemd[40293]: pam_unix(systemd-user:session): session closed for user devops
Jul  3 13:33:35 node2 sshd[41396]: Accepted publickey for devops from 192.168.2.179 port 47446 ssh2: RSA SHA256:4eU5yRUy7W0CunssYRsg6EJor1uJiMpwuo9O9cNRZ8Y
Jul  3 13:33:35 node2 systemd[41400]: pam_unix(systemd-user:session): session opened for user devops by (uid=0)
Jul  3 13:33:36 node2 sshd[41396]: pam_unix(sshd:session): session opened for user devops by (uid=0)
Jul  3 13:33:38 node2 sudo[41611]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ajfaapqtvrzxfenmfwlwwizktmftygyl ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1625333616.7582803-6947-114526206406995/AnsiballZ_setup.py
Jul  3 13:33:38 node2 sudo[41611]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jul  3 13:33:38 node2 sudo[41611]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jul  3 13:33:40 node2 sudo[41611]: pam_unix(sudo:session): session closed for user root
Jul  3 13:33:41 node2 sudo[41788]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-dkqzcrbnueofowoqkkhpeudyodulvhqg ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1625333620.7174175-6961-164463156403847/AnsiballZ_dnf.py
Jul  3 13:33:41 node2 sudo[41788]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jul  3 13:33:41 node2 sudo[41788]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jul  3 13:33:44 node2 sudo[41788]: pam_unix(sudo:session): session closed for user root
Jul  3 13:33:45 node2 sudo[41921]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-kfzgvdmxaxyphrkjxwqgykkcnwcjwsyk ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1625333624.7691586-6972-64389091365389/AnsiballZ_stat.py
Jul  3 13:33:45 node2 sudo[41921]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jul  3 13:33:45 node2 sudo[41921]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jul  3 13:33:45 node2 sudo[41921]: pam_unix(sudo:session): session closed for user root
Jul  3 13:33:46 node2 sudo[41992]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-dpdqgylaidiavolqikobrxbpvcyjzwka ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1625333624.7691586-6972-64389091365389/AnsiballZ_file.py
Jul  3 13:33:46 node2 sudo[41992]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jul  3 13:33:46 node2 sudo[41992]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jul  3 13:33:46 node2 sudo[41992]: pam_unix(sudo:session): session closed for user root
Jul  3 13:33:48 node2 sudo[42125]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-albtjtzzhrivteiavauuhrlrfbjsmsim ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1625333627.0197973-6987-219476917942342/AnsiballZ_systemd.py
Jul  3 13:33:48 node2 sudo[42125]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jul  3 13:33:48 node2 sudo[42125]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jul  3 13:33:48 node2 sudo[42125]: pam_unix(sudo:session): session closed for user root
Jul  3 13:33:49 node2 sudo[42262]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-lyyghvvqxhxkhwfpdzjpvoqitoklquhp ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1625333628.8820791-6987-1766940109517/AnsiballZ_systemd.py
Jul  3 13:33:49 node2 sudo[42262]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jul  3 13:33:49 node2 sudo[42262]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jul  3 13:33:50 node2 sudo[42262]: pam_unix(sudo:session): session closed for user root
Jul  3 13:33:51 node2 sudo[42399]:  devops : TTY=pts/0 ; PWD=/home/devops ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ppnlefqyfbojxlvnoplpsjdrcnqnpqnr ; /usr/libexec/platform-python /home/devops/.ansible/tmp/ansible-tmp-1625333630.3243895-7017-91135450805352/AnsiballZ_firewalld.py
Jul  3 13:33:51 node2 sudo[42399]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Jul  3 13:33:51 node2 sudo[42399]: pam_unix(sudo:session): session opened for user root by devops(uid=0)
Jul  3 13:33:52 node2 sudo[42399]: pam_unix(sudo:session): session closed for user root
Jul  3 13:34:52 node2 sshd[41422]: Received disconnect from 192.168.2.179 port 47446:11: disconnected by user
Jul  3 13:34:52 node2 sshd[41422]: Disconnected from user devops 192.168.2.179 port 47446
Jul  3 13:34:52 node2 sshd[41396]: pam_unix(sshd:session): session closed for user devops
Jul  3 13:34:52 node2 systemd[41409]: pam_unix(systemd-user:session): session closed for user devops
Jul 10 09:26:06 node2 polkitd[871]: Loading rules from directory /etc/polkit-1/rules.d
Jul 10 09:26:06 node2 polkitd[871]: Loading rules from directory /usr/share/polkit-1/rules.d
Jul 10 09:26:06 node2 polkitd[871]: Finished loading, compiling and executing 10 rules
Jul 10 09:26:06 node2 polkitd[871]: Acquired the name org.freedesktop.PolicyKit1 on the system bus
Jul 10 09:26:14 node2 sshd[1058]: Server listening on 0.0.0.0 port 22.
Jul 10 09:26:14 node2 sshd[1058]: Server listening on :: port 22.
Jul 10 09:26:25 node2 systemd[1483]: pam_unix(systemd-user:session): session opened for user gdm by (uid=0)
Jul 10 09:26:27 node2 gdm-launch-environment][1459]: pam_unix(gdm-launch-environment:session): session opened for user gdm by (uid=0)
Jul 10 09:26:41 node2 polkitd[871]: Registered Authentication Agent for unix-session:c1 (system bus name :1.45 [/usr/bin/gnome-shell], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Jul 10 09:33:31 node2 systemd[2492]: pam_unix(systemd-user:session): session opened for user root by (uid=0)
Jul 10 09:33:32 node2 gdm-password][2483]: pam_unix(gdm-password:session): session opened for user root by (uid=0)
Jul 10 09:33:35 node2 polkitd[871]: Registered Authentication Agent for unix-session:2 (system bus name :1.226 [/usr/bin/gnome-shell], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Jul 10 09:35:52 node2 polkitd[892]: Loading rules from directory /etc/polkit-1/rules.d
Jul 10 09:35:52 node2 polkitd[892]: Loading rules from directory /usr/share/polkit-1/rules.d
Jul 10 09:35:52 node2 polkitd[892]: Finished loading, compiling and executing 10 rules
Jul 10 09:35:52 node2 polkitd[892]: Acquired the name org.freedesktop.PolicyKit1 on the system bus
Jul 10 09:35:56 node2 sshd[1062]: Server listening on 0.0.0.0 port 22.
Jul 10 09:35:56 node2 sshd[1062]: Server listening on :: port 22.
Jul 10 09:36:02 node2 systemd[1474]: pam_unix(systemd-user:session): session opened for user gdm by (uid=0)
Jul 10 09:36:03 node2 gdm-launch-environment][1447]: pam_unix(gdm-launch-environment:session): session opened for user gdm by (uid=0)
Jul 10 09:36:15 node2 polkitd[892]: Registered Authentication Agent for unix-session:c1 (system bus name :1.43 [/usr/bin/gnome-shell], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Jul 10 11:12:33 node2 sshd[3244]: Accepted publickey for ansible from 192.168.1.136 port 36306 ssh2: RSA SHA256:jpchiL+jLX3smTuII7SubLqdvcmq8e3I+5HSG4oUreQ
Jul 10 11:12:34 node2 systemd[3248]: pam_unix(systemd-user:session): session opened for user ansible by (uid=0)
Jul 10 11:12:35 node2 sshd[3244]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Jul 10 11:13:41 node2 sshd[3271]: Received disconnect from 192.168.1.136 port 36306:11: disconnected by user
Jul 10 11:13:41 node2 sshd[3271]: Disconnected from user ansible 192.168.1.136 port 36306
Jul 10 11:13:41 node2 sshd[3244]: pam_unix(sshd:session): session closed for user ansible
Jul 10 11:13:41 node2 systemd[3256]: pam_unix(systemd-user:session): session closed for user ansible
Jul 17 10:50:08 node2 polkitd[862]: Loading rules from directory /etc/polkit-1/rules.d
Jul 17 10:50:08 node2 polkitd[862]: Loading rules from directory /usr/share/polkit-1/rules.d
Jul 17 10:50:08 node2 polkitd[862]: Finished loading, compiling and executing 10 rules
Jul 17 10:50:08 node2 polkitd[862]: Acquired the name org.freedesktop.PolicyKit1 on the system bus
Jul 17 10:50:18 node2 sshd[1055]: Server listening on 0.0.0.0 port 22.
Jul 17 10:50:18 node2 sshd[1055]: Server listening on :: port 22.
Jul 17 10:50:29 node2 systemd[1477]: pam_unix(systemd-user:session): session opened for user gdm by (uid=0)
Jul 17 10:50:31 node2 gdm-launch-environment][1453]: pam_unix(gdm-launch-environment:session): session opened for user gdm by (uid=0)
Jul 17 10:50:46 node2 polkitd[862]: Registered Authentication Agent for unix-session:c1 (system bus name :1.42 [/usr/bin/gnome-shell], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Jul 17 11:10:48 node2 systemd[2614]: pam_unix(systemd-user:session): session opened for user root by (uid=0)
Jul 17 11:10:49 node2 gdm-password][2605]: pam_unix(gdm-password:session): session opened for user root by (uid=0)
Jul 17 11:10:53 node2 polkitd[862]: Registered Authentication Agent for unix-session:2 (system bus name :1.211 [/usr/bin/gnome-shell], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Jul 17 11:16:35 node2 polkitd[870]: Loading rules from directory /etc/polkit-1/rules.d
Jul 17 11:16:35 node2 polkitd[870]: Loading rules from directory /usr/share/polkit-1/rules.d
Jul 17 11:16:35 node2 polkitd[870]: Finished loading, compiling and executing 10 rules
Jul 17 11:16:35 node2 polkitd[870]: Acquired the name org.freedesktop.PolicyKit1 on the system bus
Jul 17 11:16:44 node2 sshd[1056]: Server listening on 0.0.0.0 port 22.
Jul 17 11:16:44 node2 sshd[1056]: Server listening on :: port 22.
Jul 17 11:16:55 node2 systemd[1472]: pam_unix(systemd-user:session): session opened for user gdm by (uid=0)
Jul 17 11:16:56 node2 gdm-launch-environment][1446]: pam_unix(gdm-launch-environment:session): session opened for user gdm by (uid=0)
Jul 17 11:17:09 node2 polkitd[870]: Registered Authentication Agent for unix-session:c1 (system bus name :1.41 [/usr/bin/gnome-shell], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Jul 17 11:27:08 node2 sshd[2501]: Accepted publickey for ansible from 192.168.2.179 port 55652 ssh2: RSA SHA256:jpchiL+jLX3smTuII7SubLqdvcmq8e3I+5HSG4oUreQ
Jul 17 11:27:09 node2 systemd[2506]: pam_unix(systemd-user:session): session opened for user ansible by (uid=0)
Jul 17 11:27:10 node2 sshd[2501]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Jul 17 11:28:19 node2 sshd[2527]: Received disconnect from 192.168.2.179 port 55652:11: disconnected by user
Jul 17 11:28:19 node2 sshd[2527]: Disconnected from user ansible 192.168.2.179 port 55652
Jul 17 11:28:20 node2 sshd[2501]: pam_unix(sshd:session): session closed for user ansible
Jul 17 11:28:20 node2 systemd[2515]: pam_unix(systemd-user:session): session closed for user ansible
Jul 17 12:08:45 node2 sshd[3109]: Connection closed by authenticating user root 192.168.2.179 port 55664 [preauth]
Jul 17 12:09:31 node2 sshd[3111]: Connection closed by authenticating user root 192.168.2.179 port 55674 [preauth]
Jul 17 12:10:38 node2 sshd[3129]: Accepted publickey for ansible from 192.168.2.179 port 55684 ssh2: RSA SHA256:jpchiL+jLX3smTuII7SubLqdvcmq8e3I+5HSG4oUreQ
Jul 17 12:10:39 node2 systemd[3134]: pam_unix(systemd-user:session): session opened for user ansible by (uid=0)
Jul 17 12:10:39 node2 sshd[3129]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Jul 17 12:11:35 node2 sshd[3367]: Connection closed by authenticating user root 192.168.2.179 port 55696 [preauth]
Jul 17 12:11:47 node2 sshd[3156]: Received disconnect from 192.168.2.179 port 55684:11: disconnected by user
Jul 17 12:11:47 node2 sshd[3156]: Disconnected from user ansible 192.168.2.179 port 55684
Jul 17 12:11:47 node2 sshd[3129]: pam_unix(sshd:session): session closed for user ansible
Jul 17 12:11:47 node2 systemd[3143]: pam_unix(systemd-user:session): session closed for user ansible
Jul 17 12:12:01 node2 sshd[3396]: Accepted password for root from 192.168.2.179 port 55704 ssh2
Jul 17 12:12:02 node2 systemd[3401]: pam_unix(systemd-user:session): session opened for user root by (uid=0)
Jul 17 12:12:02 node2 sshd[3396]: pam_unix(sshd:session): session opened for user root by (uid=0)
